feat: PresignedUrl을 사용하여 이미지 업로드 기능 구현
depromeet/10mm-server pull request #106
Opened 2024-01-05 06:41 UTC by kdomo

## 🌱 관련 이슈
- close #101 

## 📌 작업 내용 및 특이사항
- StorageConfig에서 기존 AWS SDK를 사용해 PresignedUrlRequest를 만들 때 endpoint가 AWS로 되어있어서 endpoint를 환경변수로 추가하고 NCP endpoint를 넣어주었습니다.
- PresignedUrl 생성 시 ExpireTime을 30초로 설정하였습니다
- 파일 디렉토리는 `/환경(ex:local, dev, prod)/members/{memberId}/ImageType(ex:mission_record)/{targetId}/image.{imageFileExtension(ex:jpeg, jpg, png)}`와 같습니다. 여기서 targetId는 ImageType에 따라 달라집니다.
- PresignedUrl 생성 시 해당 미션 기록의 이미지 상태를 `PENDING` 상태로 변경
- PresignedUrl 업로드 완료 처리에서 미션 기록의 업데이트상태를 `COMPLETE`로 변경함과 동시에 미션 일지와 이미지를 업데이트합니다.

## 📝 참고사항
- 

## 📚 기타
- Test 작성 전까지 draft 걸어둘게용

2024-01-06 06:34 UTC, uwoobeat requested changes

2024-01-06 06:34 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
> +    public void updateUploadStatusComplete(String remark, String imageUrl) {
이미 `COMPLETED` 인 경우 다시 완료처리할 수 없도록 예외 발생시키는 게 좋을 것 같습니다

2024-01-06 06:49 UTC, kdomo commented
벨리데이션 추가 예정
- 이미 COMPLETED 인 경우 다시 완료처리할 수 없도록 예외 발생
- 해당 미션이 접속한 유저와 일치 하지 않을 때 예외 발생

2024-01-06 07:51 UTC, uiurihappy reviewed
리뷰 달았어용

2024-01-06 07:51 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/image/domain/ImageFileExtension.java
만약 Request 받은 이미지의 확장자가 
정의된 3개의 확장자 중에서 존재하지 않으면 어떻게 되나요??

2024-01-06 07:54 UTC, kdomo commented on src/main/java/com/depromeet/domain/image/domain/ImageFileExtension.java
JSON parse error를 응답합니다아
![image](https://github.com/depromeet/10mm-server/assets/64088250/41e63f2a-14f9-4715-91d0-6290ac52e9bd)

2024-01-06 07:57 UTC, kdomo commented on src/main/java/com/depromeet/domain/image/domain/ImageFileExtension.java
프론트와 이미지 확장자 스펙 논의 필요

2024-01-08 14:03 UTC, uiurihappy requested changes

2024-01-08 14:03 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/image/application/ImageService.java
클래스 전체를 `@Transactional` 감싸는 것은 어떠실까요??
조회만 하는 서비스 코드 구현 시에는 Trasactional readonly = true로 하는 게 어떨까해서요!

2024-01-08 14:07 UTC, kdomo commented on src/main/java/com/depromeet/domain/image/api/ImageController.java
넘버링 해놓을게용, endpoint는 images제거 하도록 하겠슴니당

2024-01-08 14:07 UTC, kdomo commented on src/main/java/com/depromeet/domain/image/application/ImageService.java
오 이부분 놓쳤네용 감사함니다

2024-01-09 12:39 UTC, kdomo commented on src/main/java/com/depromeet/domain/image/domain/ImageFileExtension.java
<img src="https://github.com/depromeet/10mm-server/assets/64088250/9d95e213-7e55-49d1-824a-b0df9b476160" alt="slack논의결과" width="400"/>

(24.01.08) 논의완료
기존과 같이 가면 될 것 같슴니당

2024-01-09 15:45 UTC, uiurihappy approved these changes
반영된 거 확인이랑 확장자 확정 내용도 확인했습니다:)
✅LGTM✅

2024-01-10 12:37 UTC, uwoobeat requested changes

2024-01-10 12:41 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
> +        mission.validateUserMismatch(member);
ImageService와 MissionRecordService 에서 중복으로 사용되서 Mission으로 빼두었는데,
Mission 엔티티 책임이 아닌거같네용
수정해두겠습니다

2024-01-10 12:41 UTC, uwoobeat approved these changes
lgtm

2024-01-10 14:20 UTC, merged