feat: 미션 내역 리스트 조회
depromeet/10mm-server pull request #107
Opened 2024-01-05 14:56 UTC by uiurihappy

## 🌱 관련 이슈
- close #86 

## 📌 작업 내용 및 특이사항
- yearMonth로 년월 데이터 받아 처리

## 📝 참고사항
- 

## 📚 기타
-

2024-01-06 07:52 UTC, kdomo requested changes

2024-01-06 07:52 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
> +            @RequestParam("yearMonth") String yearMonth) {
String이 아닌 YearMonth로 받으면 좋을 것 같아용
[Spring Boot에서 yyyy-MM 포맷으로 날짜 받고싶을때-기억보단 기록을](https://jojoldu.tistory.com/527)

2024-01-06 07:52 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
> +    List<MissionRecord> findAllByMissionId(Long missionId, YearMonth yearMonth);
`findAllByMissionIdAndYearMonth`와 같이 메소드 네이밍이 좀 더 정확했으면 좋겠어용

2024-01-06 07:52 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
> +    }
controller에서 YearMonth로 받게되면 해당 부분 필요없을 것 같아용

2024-01-06 07:52 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
> +        YearMonth yearMonthObj = YearMonth.parse(yearMonth);
YearMonth로 받으면 요것도 사라지겠네용

2024-01-06 07:52 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordFindResponse.java
> +        String remart,
여기 오타있어용

2024-01-06 07:52 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordFindResponse.java
> +        int missionDay,
요게 n일차에 해당하는건가요?

2024-01-06 07:52 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
> +    @GetMapping
미션 기록 조회에 기본 endpoint는 미션 단건이 더 맞는거같아서 아래와 같이 바꾸는건 어떨까요?
(미션 상세 조회도 스펙에 있기도하고)

```suggestion
    @Operation(summary = "미션 기록 캘린더 조회", description = "년, 월을 입력받아 미션 기록을 캘린더로 조회합니다")
    @GetMapping("/calender")
```

2024-01-06 07:52 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
> +    }
요 부분 설명 가능할까용?

2024-01-06 07:55 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
> +    List<MissionRecord> findAllByMissionId(Long missionId, YearMonth yearMonth);
아 그러네용 수정해두겠습니다!

2024-01-06 07:57 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordFindResponse.java
> +        String remart,
mart ㅋㅋㅋㅋㅋㅋㅋ 수정해둘게요 👍

2024-01-06 07:58 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordFindResponse.java
> +        int missionDay,
n일차는 미션 내역 details에서 다루기만 하면 되서 
missionDay는 프론트엔드에서 캘린더 매핑하는 데에 이점을 가져갈 수 있다해서
저렇게 약속했습니다!

2024-01-06 08:00 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
> +    @GetMapping
훔.. 이건 재현님도 같이 의논을 해봐야 할 거 같은데
@uwoobeat 어떻게 생각하신가요?

2024-01-06 08:04 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
> +    }
missionRecord 내에 createdAt와 년월 대조하는 쿼리로
```sql
where
        m1_0.mission_id=? 
        and (
            (
                year(m1_0.created_at)*100
            )+month(m1_0.created_at)
        )=? 
```
이렇게 쿼리가 사용되어 createdAt의 년이 2024이면 * 100으로 202400이 될테고,
createdAt의 월로 01이면 그대로 +를 진행해서 202401로 equal 연산을 진행하게 됩니다!

혹시 다른 방향성이나 피드백도 있으시다면 알려주세용

2024-01-06 10:56 UTC, uwoobeat requested changes

2024-01-06 10:56 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
> +    }
이건 어떨까요
```java
        return missionRecord.startedAt.year().eq(yearMonth.getYear())
                .and(missionRecord.startedAt.month().eq(yearMonth.getMonthValue()));
```

테스트는 안해봤는데 대충 year끼리 && month끼리 비교한 겁니다

2024-01-06 10:56 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
> +    @GetMapping
이거는 면대면으로 이야기하는 게 좋을 것 같아요
이따가 시간나면 게더에서 이야기 ㄱㄱ하시죠

2024-01-06 10:59 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
> +    }
저도 이 방법을 사용하고 테스트 해봤는데 잘 되긴 했습니다.
그러나 yyyy-MM 형식값을 한번에 비교하는 방법이 낫다고 생각해서 위 같이 구현을 했었습니다!

2024-01-08 05:48 UTC, uiurihappy commented
@kdomo 
도모님 일단 리뷰 작성하신 내용은 반영되었는데, @uwoobeat 재현님과 둘이서 논의한 내용은
일단 캘린더라고 명시하는 것보다 미션 내역 조회 리스트에 초점을 두고 개발하는 것이 낫다고 얘기했어요

엔드포인트에 calendar로 명시하는 것은 오로지 기획서에 있는 캘린더 뷰에 의존적이고, 
추후 캘린더 뷰 외 미션 내역 리스트가 필요한 기획이 있는 경우 그때 또 추가 논의로 엔드포인트를 가르는 방향으로 가져가는 것이 어떠실까요??

2024-01-08 08:45 UTC, kdomo approved these changes
굳굳 좋아용👍🏻

2024-01-09 10:16 UTC, uwoobeat approved these changes
lgtm

2024-01-09 15:02 UTC, merged