feat: 미션 내역 상세 조회 구현
depromeet/10mm-server pull request #115
Opened 2024-01-09 16:34 UTC by uiurihappy

## 🌱 관련 이슈
- close #110 

## 📌 작업 내용 및 특이사항
- 미션 내역 상세 조회 구현으로 findById로 구현
- 미션 수행한 시간(분)은 duration 값을 toMinutes()로 구현
- 미션 시작한 지 D+Day는 Duration의 between 메서드를 활용해 toDays()로 Day 값 return

## 📝 참고사항
- MissionRecordFindOneResponse로 단건 조회에 대한 DTO를 생성했습니다.
- 이전 미션 내역 조회 PR(#107) 에서 미처 구현하지 못한 사항도 수정했습니다

## 📚 기타
-

2024-01-09 18:04 UTC, kdomo approved these changes
고생하셨습니다🙇🏻

2024-01-09 18:04 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordFindOneResponse.java
> +    }
응답값 잘 넘어오는지 controller 테스트 있으면 좋을 것 같네용👍🏻

2024-01-10 03:29 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordFindOneResponse.java
> +    }
앗 그러면 금일 이슈 생성해서 작성하도록 하겠습니다!

2024-01-10 13:01 UTC, uwoobeat requested changes

2024-01-10 13:01 UTC, uwoobeat commented on src/main/java/com/depromeet/global/error/exception/ErrorCode.java
>      MISSION_RECORD_USER_MISMATCH(HttpStatus.BAD_REQUEST, "미션을 생성한 유저와 로그인된 계정이 일치하지 않습니다"),
요거는 403으로 보내줘야 할 것 같습니다

2024-01-10 13:01 UTC, uwoobeat approved these changes
lgtm

2024-01-10 13:24 UTC, merged