feat: OIDC 소셜 로그인 구현
depromeet/10mm-server pull request #119
Opened 2024-01-10 01:56 UTC by uwoobeat

## 🌱 관련 이슈
- close #62

## 📌 작업 내용 및 특이사항
- OIDC 인증 구현
- JWT 인증인가 구현
- 회원가입 API 구현

## 📝 참고사항
- 작업사항이 많아 코어타임 때 구두로 이야기하도록 하겠습니다...!

## 📚 기타
- 애플 로그인의 경우 개발자 계정 이슈로 작업 불가

2024-01-11 10:34 UTC, kdomo requested changes

2024-01-11 10:34 UTC, kdomo commented on src/main/java/com/depromeet/domain/auth/api/AuthController.java
> +@Tag(name = "[인증]", description = "인증 관련 API")
1번 넘버링 부탁드립니다잇

2024-01-11 10:34 UTC, kdomo commented on src/main/java/com/depromeet/domain/auth/application/JwtTokenService.java
> +        Long memberId = jwtTokenProvider.parseRefreshToken(refreshToken);
parseRefreshToken 메서드는 customException을 내보내고있는데 throws에 NoSuchElementException은 어디서 나온건가용??

2024-01-11 10:34 UTC, kdomo commented on src/main/java/com/depromeet/domain/auth/application/JwtTokenService.java
> +        return memberRepository.findById(memberId).orElseThrow();
요기 에러처리 안된건가용?

2024-01-11 10:34 UTC, kdomo commented on src/main/java/com/depromeet/domain/member/domain/Member.java
> +        this.profile = new Profile(nickname, null);
object storage에 user default이미지 넣어두고 해당 값 상수로 넣으면 좋을 것 같습니다👍🏻👍🏻

2024-01-11 10:34 UTC, kdomo commented on src/main/java/com/depromeet/global/common/constants/SecurityConstants.java
> +}
저는 상수를 enum으로 관리했는데,
enum으로 관리하면 인스턴스 생성, 상속을 방지하며 상수값의 타입 안전성이 보장되어서 좋은 것 같아용

2024-01-11 10:34 UTC, kdomo commented on src/main/java/com/depromeet/global/config/security/WebSecurityConfig.java
> +        //        .permitAll());
요기쪽 `/v1/**` 사용하지 않고있고, 사용되지 않는 주석 제거 부탁드림니당
추 후 새로운 이슈파서 사용되는 url 허용해줘야할거같아용

2024-01-11 10:34 UTC, kdomo commented on src/main/java/com/depromeet/global/config/security/WebSecurityConfig.java
> +                                .successHandler(customOidcAuthenticationSuccessHandler));
실패 핸들러는 구현하지 않아도 괜찮을까요?
resource 서버에서 제대로된응답이 불가능할때 예외처리도 필요해보입니당!

2024-01-11 10:34 UTC, kdomo commented on src/main/java/com/depromeet/global/config/security/WebSecurityConfig.java
> +        http.addFilterAfter(jwtAuthenticationFilter, LogoutFilter.class);
지금은 한개여서 괜찮을 것 같은데 추후 필터가 추가된다면 config를 따로 빼서 관리하는것도 좋을거같아용

2024-01-11 10:34 UTC, kdomo commented on src/main/java/com/depromeet/global/error/exception/ErrorCode.java
>      ;
MissionRecord쪽 말고 Member쪽에 추가 부탁드립니다잇

2024-01-11 10:34 UTC, kdomo commented on src/main/java/com/depromeet/global/security/CustomOidcAuthenticationSuccessHandler.java
> +        log.info("authentication success");
log 남겨놓은거 좋은 것 같습니다, 다만 내용이 조금 빈약하다고 생각되어용
저는 보통 로그를 남길때 어떤 클래스의 어떤 메서드에서 어떤 값을 가지고있는지 남겨놓는데용
해당 부분에서는 어떤 유저의 인증이 성공했는지에 대한 값도 넣으면 좋을 것 같아용

2024-01-11 10:34 UTC, kdomo commented on src/main/java/com/depromeet/global/security/JwtAuthenticationFilter.java
> +        }
재발급 후에 쿠키에 응답해주는 과정이 필요할 것 같아용

2024-01-11 10:34 UTC, kdomo commented on src/test/java/com/depromeet/TestRedisConfig.java
> +public class TestRedisConfig {}
굳굳 👍🏻

2024-01-11 10:34 UTC, kdomo commented on src/main/resources/application.yml
> +      - security
include 좋네용👍🏻

2024-01-11 10:56 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/auth/application/JwtTokenService.java
> +        Long memberId = jwtTokenProvider.parseRefreshToken(refreshToken);
아 이 부분 TODO로 해놓고 수정하려고 했는데 빼먹었네요. 

`orElseThrow()`에서 `CustomException(ErrorCode.MEMBER_NOT_FOUND`으로 던지는 대신 디폴트 예외엔 `NoSuchElementException`으로 던지도록 했습니다. 

이유는 CustomException은 클라이언트한테 어떤 status code를 내려줄 것인지도 결정하고 있는데, `getMemberFrom` 에서 발생한 예외는 `JwtAuthenticationFilter` 로 가는데, 여기서 어떤 예외가 발생하든 간에 인증 실패이므로 401을 내려줘야 합니다. 근데 `MEMBER_NOT_FOUND` 를 던지면 404가 나가니까 NoSuchElementException으로 던지고 `CustomAuthenticationEntryPoint` 에서 이걸 잡아서 401로 매핑해줄 계획이었어요.

근데 인증 과정에서 발생하는 예외를 잡는 CustomAuthenticationEntryPoint를 아직 구현을 안해서 이 부분은 추가로 작업하도록 할게요.

2024-01-11 10:57 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/auth/application/JwtTokenService.java
> +        return memberRepository.findById(memberId).orElseThrow();
커스텀 예외로 던지고 AuthenticationEntryPoint에서 잡아서 401로 보낼게요~

2024-01-11 11:04 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/member/domain/Member.java
> +        this.profile = new Profile(nickname, null);
아 이거는 나중에 프로바이더에서 제공하는 프로필 이미지 복사해서 object storage에 넣는 로직도 추가 작업할 예정인데, 이렇게 하면 `register` 호출했을 때 url이 다시 null로 덮여씌워지는 문제가 있거든요. 그래서 TODO 작성해둔 거였어요

그리고 default 이미지의 경우 프론트에서 가지고 있고 서버에서는 null로 두는게 좋을 것 같습니다!

2024-01-11 11:17 UTC, kdomo commented on src/main/java/com/depromeet/domain/member/domain/Member.java
> +        this.profile = new Profile(nickname, null);
말씀하신대로 디폴트 이미지는 프론트에서 가지고있는게 좋겠네용
추 후에 회원가입 단계에서 프로필 이미지도 설정 가능하도록 기획하고 있어서 그때 추가하면 좋을 것 같네용

2024-01-11 11:17 UTC, kdomo commented on src/main/java/com/depromeet/domain/auth/application/JwtTokenService.java
> +        Long memberId = jwtTokenProvider.parseRefreshToken(refreshToken);
NoSuchElementException는 어디서 던지나용 ?

2024-01-11 11:18 UTC, uwoobeat commented on src/main/java/com/depromeet/global/common/constants/SecurityConstants.java
> +}
음 이것도 enum으로 했다가 일반 클래스로 바꾼 건데요, enum을 쓰니까 `SecurityConstants.TOKEN_ROLE_NAME.getValue()` 와 같이 코드가 너무 장황해져서 별로더라고요.

일반 클래스로 만들고 static import하면 클래스 이름 없이 쓸 수 있어서 좋은 것 같아요.

```java
    private void setTokenPairToResponseHeader(
            HttpServletResponse response, String accessToken, String refreshToken) {
        response.setHeader(ACCESS_TOKEN_HEADER, TOKEN_PREFIX + accessToken);
        response.setHeader(REFRESH_TOKEN_HEADER, TOKEN_PREFIX + refreshToken);
    }
```

한 line에서 상수가 여러 개 쓰이는 경우에는 더 이점이 있는 것 같아요.
물론 enum을 아예 쓰면 안된다는 건 아니고, 각자 장단점이 있다고 봅니다.

1. 싱글톤을 보장해야 하거나
2. `valueOf()` 같이 enum 상수에 대한 검색이 필요하거나 (e.g. `SwaggerUrlConstants`)
3. 의미있는 값들을 하나의 상수로 묶어야 하는 경우 (여러 개의 필드가 존재)

이고 언급해주신 인스턴스화 막기 / 상속 방지는 일반 클래스에서도 구현 가능합니다.
-> 전자는 기본 생성자 private으로 하면 되고(추가 commit 해놨습니다), 상속 방지는 final 클래스로 만들면 됩니다 (이미 작업해둠)

enum 타입의 타입 안전성의 경우 메서드 시그니처에 사용되는 경우에만 이점이 있다고 봐서 상수 클래스에서는 써먹기 어려울 것 같습니다


따라서 앞으로는 enum 상수 클래스는 위 케이스에 해당되는 경우에만 사용하고 나머지는 일반 클래스로 쓰면 어떨까 싶은데 어떻게 생각하시나요?

2024-01-11 11:23 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/auth/application/JwtTokenService.java
> +        Long memberId = jwtTokenProvider.parseRefreshToken(refreshToken);
`orElseThrow()`가 디폴트로 던지는 예외가 `NoSuchElementException` 이에용

2024-01-11 11:43 UTC, uwoobeat commented on src/main/java/com/depromeet/global/security/JwtAuthenticationFilter.java
> +        }
지금 리프레시 토큰의 경우 쿠키를 쓰지 않고 `Refresh-Token` 커스텀 헤더로 넘겨주고 있는데, 쿠키에 담아서 넘겨주도록 바꿔볼게요~

2024-01-11 11:44 UTC, kdomo commented on src/main/java/com/depromeet/global/common/constants/SecurityConstants.java
> +}
좋습니당 추가 커밋 확인했습니당

2024-01-11 11:45 UTC, kdomo commented on src/main/java/com/depromeet/global/security/CustomOidcAuthenticationSuccessHandler.java
> +        log.info("authentication success");
로그 정책 논의 해봅시당

2024-01-13 05:06 UTC, uiurihappy reviewed
리뷰 달았어용
카카오에 대한 로직은 안보이는데 나중에 설명이나 로직 추가 예정인지 궁금해용

2024-01-13 05:06 UTC, uiurihappy commented on src/main/java/com/depromeet/global/config/security/WebSecurityConfig.java
> +        //        .permitAll());
URL 따로 할당하는 배열을 선언해도 괜찮을 거 같아용

2024-01-14 18:13 UTC, uwoobeat commented on src/main/java/com/depromeet/global/security/AppleRequestEntityConverter.java
> +
네 요거는 임시로 긁어온 코드고 지금은 `CustomRequestEntityConverterV2` 보심 돼요

2024-01-14 18:14 UTC, uwoobeat commented on src/main/resources/application-local.yml
>      show-sql: ${SHOW_SQL:true}
ddl-auto의 경우 컬럼 변동사항은 반영해주지 않아서 create로 해주었습니다

2024-01-14 18:19 UTC, uwoobeat commented on src/main/resources/application-security.yml
> +  issuer: ${JWT_ISSUER:}
음 2시간까지 늘려도 괜찮을 것 같네요.
리프레시 토큰이 레디스에 있어서 접근 비용이 비싼건 아니지만 그래도 엑세스 토큰이 유효한 상태에서 재발급해주는 로직을 쓰는 편이 더 효율적이긴 하니까요. 수정해두겠습니다

2024-01-14 19:43 UTC, uwoobeat commented on src/main/java/com/depromeet/global/security/JwtAuthenticationFilter.java
> +        }
아 둘 중 하나라도 null이면 통과... 인데 잘못 적었네요

2024-01-14 19:48 UTC, merged