feat: 미션 내역 수정 구현
depromeet/10mm-server pull request #123
Opened 2024-01-10 10:09 UTC by uiurihappy

## 🌱 관련 이슈
- close #112 

## 📌 작업 내용 및 특이사항
- 기록된 미션 내역 일지를 수정하는 API 구현으로 변경감지 사용

## 📝 참고사항
- 

## 📚 기타
-

2024-01-10 13:13 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordUpdateResponse.java
> +    public MissionRecordUpdateResponse(MissionRecord missionRecord) {
정적 팩토리 메서드로 만들어주세용

2024-01-10 13:34 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordUpdateResponse.java
> +    public MissionRecordUpdateResponse(MissionRecord missionRecord) {
기존있던 미션 수정 API에도 정적으로 만들어 놓을게요~

2024-01-10 13:45 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
> +        missionRecord.updateMissionRecord(request);
소유권 검증이라 하면 미션 내역(missionRecord)과 Member에 대해 소유권 검증이신 거 같은데,
missionRecord에는 Member와 연관관계가 없어서 소유권 검증이 어렵지 않을까요?

2024-01-10 13:46 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
> +    public MissionRecordUpdateResponse updateMissionRecord(
이슈에 서비스 레이어 테스트 코드 작성해놓겠습니다~

2024-01-10 14:31 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordUpdateResponse.java
> +                String remark) {
상세로 다시 이동되는 걸로 알고 있습니당

2024-01-10 14:31 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
> +    }
아 그러겠네용 수정해두겠습니다!

2024-01-10 14:32 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/dto/response/MissionUpdateResponse.java
>          }
저번에 MissionServiceTest 코드 구현하다가 실패케이스로 혹여나 visibility가 null인 케이스도 고려해서
넣었던 걸로 기억하고 있습니당

2024-01-10 14:45 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/dto/response/MissionUpdateResponse.java
>          }
요거 해당 부분에서 null 체크가 필요한지 의문이에용
업데이트할 때 `MissionUpdateRequest`에서 MissionVisibility에 NotNull이 걸려있어서 굳이 필요 없을 것 같아용
그리고 만약 필요하다고 하더라도 Service Layer에 있어야 할 것 같아용

2024-01-10 14:47 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordUpdateResponse.java
> +                String remark) {
상세로 이동된다면
1.수정 후 프론트에서 단건 조회 API를 다시 콜하거나
2.updateResponse을 받아 바로 상세 페이지를 구성하는 경우
이렇게 두 가지가 있을 것 같아용

1번의 경우라면 recordId만 넘겨주는게 좋을 것 같아용
2번의 경우라면 해당 response에 ImageUrl도 필요할 것 같아용

이 부분은 프론트 담당자와 의논필요해보입니다!

2024-01-10 14:47 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/dto/response/MissionUpdateResponse.java
>          }
아 그러겠네요
차라리 DTO에서 거르는게 나을 거 같네용 해당 부분은 삭제하도록 하겠습니다!

2024-01-10 18:20 UTC, kdomo requested changes

2024-01-10 18:20 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
> +                missionRecord.getMission(), memberUtil.getCurrentMember());
MemberUtil에 getCurrentMember 메소드가 호출 될때마다 쿼리를 날려서
의도적으로 상단에서 변수에 할당해놓으면 좋을거같아용
```suggestion
        final Member member = memberUtil.getCurrentMember();
        MissionRecord missionRecord =
                missionRecordRepository
                        .findById(recordId)
                        .orElseThrow(() -> new CustomException(ErrorCode.MISSION_RECORD_NOT_FOUND));

        validateMissionRecordUserMismatch(
                missionRecord.getMission(), member);
```

2024-01-10 18:20 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
> +        return missionRecord.getId();
여기서 Long 타입 반환하고 있어용,
MissionRecordUpdateResponse에 recordId만 가지도록하고 MissionRecordUpdateResponse로 반환하는게 좋아보입니당👍🏻

2024-01-11 09:11 UTC, kdomo approved these changes
고생하셨습니다 🙇🏻🥹

2024-01-14 15:37 UTC, uwoobeat approved these changes
lgtm

2024-01-14 15:39 UTC, merged