feat: 전체 미션 통계 현황 API
depromeet/10mm-server pull request #177
Opened 2024-01-17 18:44 UTC by uiurihappy

## 🌱 관련 이슈
- close #150 

## 📌 작업 내용 및 특이사항
- 전체 미션 통계 현황
- 달성률 계산식: (완료된 미션 수 / 전체 미션 수 * 1000.0) / 10.0
- 전체 duration을 second로 하여 시간/분을 나눠 계산

## 📝 참고사항
- 

## 📚 기타
-

2024-01-19 07:46 UTC, kdomo requested changes

2024-01-19 07:46 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/application/MissionService.java
> +        AtomicLong sumDuration = new AtomicLong();
AtomicLong을 쓰는 이유가 궁금합니당

2024-01-19 07:46 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/application/MissionService.java
> +                            : 1;
요기 부분 설명 가능할까용?

완료된 미션 갯수라는게 조금 모호한 것 같네용
한개의 미션에 미션 기록들을 가져와서 비어있거나 한개라도 컴플리트가 아니라면 0 을 넣고있는데,
조금 이상한거같아용

2024-01-19 08:59 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/application/MissionService.java
> +        AtomicLong sumDuration = new AtomicLong();
<img width="635" alt="image" src="https://github.com/depromeet/10mm-server/assets/68099546/ab9bab51-65b0-4cc7-bc55-9cd9239eedb7">

이와 같이 stream 함수 mapToLong 내부에서 누적하려니 에러가 발생해서 AtomicLong으로 처리했었습니당 
더 좋은 방식이 있을까용??

2024-01-19 09:01 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/application/MissionService.java
> +                            : 1;
제가 이해한 건 해당 코드 플로우라 
- 일단 미션은 있는데 미션 기록 조차 없으면 그건 완료라 볼 수 없었고,
- 이미지 업로드 상태가 COMPLETE가 아닌 미션 기록에 대해서도 완료라 볼 수 없었다고 생각했었습니다

다시 이야기 해볼 필요가 있겠네용

2024-01-19 09:17 UTC, kdomo requested changes

2024-01-19 09:17 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/application/MissionService.java
> +        AtomicLong sumDuration = new AtomicLong();
오 이런게 있었군요 찾아보니까 람다의 캡처링 이라는 기능 때문에 스택에 있는 값을 복사해서 사용한다구 하네용👀
https://cobbybb.tistory.com/19

2024-01-19 09:17 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/application/MissionService.java
> +                            : 1;
allMatch를 사용하게 되면 해당 값이 모두 COMPLATE가 아닐때만 true를 주는데,
완료된 미션이라는게 하루 기준에서만 보면되는걸까요?

제가 이해한건
미션 3개를 동시에 시작하고 동시에 끝난다고 가정하였을 때,
기한은 각각 2주라고 생각한다면
14 * 3 = 42해서 42개의 미션 기록이 생성 될 수 있어서 만약 모두 다 했다면 완료된 미션기록의 개수가 42개가 되야하지 않을까 싶어용

그래야 달성률이 올바르게 나올 것 같아용

2024-01-19 09:32 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/application/MissionService.java
> +                            : 1;
그럼 미션이 아닌 미션 기록에 대한 counting과 달성률 계산이 이뤄져야겠네용
수정하고 노티줄게용:)

2024-01-20 11:08 UTC, kdomo requested changes

2024-01-20 11:08 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/application/MissionService.java
> +                Math.round((double) completeMissionSize / totalMissionRecordSize * 1000) / 10.0;
요런 계산식 들어가는 부분 private 메소드로 따로 빼면 더 좋을거같슴니당

2024-01-20 11:08 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/application/MissionService.java
> +                        .reduce(0, Long::sum);
요거 제가 한번 설명드렸던부분인데 수정 필요할 것 같아용
심볼 스택은 각 미션 기록 당 고유해야하는데, 미션의 모든 미션 기록을 합산해서 결과를 내면 의도한 로직과 달라져요!

예를들어 A라는 미션 기록에서 18초를 하고, B라는 미션에서 12초를 했을 때 A=1개, B=1개 가 생기도록하는게 의도한 로직이지만
위 코드대로 라면 모든 미션 기록의 초를 다 더하기때문에
A+B(18+12)해서 총 3개의 심볼 스택이 생기도록 되어있어서 수정이 필요해보입니당

2024-01-20 11:36 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/application/MissionService.java
> +                        .reduce(0, Long::sum);
수정했습니도 !

2024-01-20 11:49 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/application/MissionService.java
> +                                                == ImageUploadStatus.COMPLETE)
```java
missions.stream()
                        .flatMap(mission -> mission.getMissionRecords().stream())
                        .filter(
                                missionRecord ->
                                        missionRecord.getUploadStatus()
                                                == ImageUploadStatus.COMPLETE)
```

요 부분이 중복이 많은 것 같아서
```java
List<MissionRecord> completeMissionRecords = missions.stream()
                .flatMap(mission -> mission.getMissionRecords().stream())
                .filter(
                        missionRecord ->
                                missionRecord.getUploadStatus()
                                        == ImageUploadStatus.COMPLETE).collect(Collectors.toList());
```
요런식으로 먼저 선언 후에 해당 List를 사용하는건 어떻게 생각하세용?

2024-01-20 12:30 UTC, kdomo approved these changes
고생하셨슴니당

2024-01-20 12:30 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/application/MissionService.java
> +        List<MissionRecord> missionRecords =
```suggestion
        List<MissionRecord> completedMissionRecords =
```
요것만 바꾸죵

2024-01-20 15:03 UTC, merged