feat: 종료미션 DurationStatus 추가 및 스케줄러 구현
depromeet/10mm-server pull request #181
Opened 2024-01-18 15:14 UTC by uiurihappy

## 🌱 관련 이슈
- close #180 

## 📌 작업 내용 및 특이사항
- 종료미션에 대한 durationStatus 컬럼 추가
- 종료미션이 현 시간보다 낮은 일자이면 자정마다 durationStatus를 FINISHED로 갱신

## 📝 참고사항
- 

## 📚 기타
-

2024-01-18 15:34 UTC, kdomo requested changes
패키지 domain쪽보단 따로 scheduler로 빼서 거기에 넣는게 좋아보입니당
그리구 메소드명 complete보다 DurationStatus에 맞게 finish로 사용하면 어떨까용?

2024-01-18 15:34 UTC, kdomo commented on src/main/java/com/depromeet/domain/batch/cron/mission/jobs/MissionBatchJob.java
> +}
MissionBatchJob 객체 없이 MissionBatchScheduler 에서 바로 service 호출해서 사용하는게 좋아보여용

2024-01-18 15:34 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/dao/MissionRepository.java
> +    void updateMissionDurationStatusComplete();
now() 했을 때 시간이 정확히 00시 00분이 아닐 경우도 생길 것 같아서
어플리케이션 단에서 시간을 맞춰서 쿼리하는게 좋을 것 같은데 어떻게 생각하세용?

2024-01-18 15:34 UTC, kdomo commented on src/main/java/com/depromeet/TenminuteApplication.java
> +@EnableScheduling
Config로 따로 빼도 좋을 것 같아용

2024-01-18 16:35 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/batch/cron/mission/jobs/MissionBatchJob.java
> +}
배치 영역과 스케줄러 영역 분리가 필요할까봐 했었는데 지금은 없이하는게 나을 듯 하네용👍

2024-01-18 16:36 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/dao/MissionRepository.java
> +    void updateMissionDurationStatusComplete();
넵 저도 좋다고 생각해용

2024-01-18 21:15 UTC, kdomo requested changes

2024-01-19 03:21 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/dao/MissionRepository.java
> +    void updateFinishedDurationStatus(@Param("today") LocalDateTime today);
좋아용 반영해서 push 했습니다!

2024-01-19 08:07 UTC, kdomo approved these changes
LGTM~
고생하셨습니당

2024-01-19 08:51 UTC, merged