feat: 친구 미션 목록
depromeet/10mm-server pull request #196
Opened 2024-01-22 06:47 UTC by uiurihappy

## 🌱 관련 이슈
- close #188 

## 📌 작업 내용 및 특이사항
- 엔드포인트: `/missions/friend?nickname={nickname}
- QueryString으로 nickname 요청받도록
- existsByFollowerIdAndFollowingId로 팔로우 관계 boolean형 인자를 사용해 where visibility in (ALL, FOLLOW or null) 관계 정의 
- symbolStack 구하는 계산식 메서드 분리, mission의 완료 여부는 동일하게 사용
- 완료된 미션은 상단으로 올리게 Comparator.comparing을 사용
- symbolStack과 missions의 response DTO 선언하여 프론트에게 response

## 📝 참고사항
- memberUtil에서 findByProfileNickname로 nickname으로 유저 조회

## 📚 기타
-

2024-01-22 11:10 UTC, kdomo requested changes

2024-01-22 11:10 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/dto/response/FollowMissionFindAllResponse.java
> +    }
[정적 팩토리 메서드 네이밍 규칙](https://inpa.tistory.com/entry/GOF-%F0%9F%92%A0-%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C-%EC%83%9D%EC%84%B1%EC%9E%90-%EB%8C%80%EC%8B%A0-%EC%82%AC%EC%9A%A9%ED%95%98%EC%9E%90#%EC%A0%95%EC%A0%81_%ED%8C%A9%ED%86%A0%EB%A6%AC_%EB%A9%94%EC%84%9C%EB%93%9C_%EB%84%A4%EC%9D%B4%EB%B0%8D_%EA%B7%9C%EC%B9%99)에 따라 from보다는 다른 네이밍을 사용하는게 좋다고 생각함니당

2024-01-22 11:10 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/dto/response/MissionFindAllResponse.java
> +    }
null 전파를 객체 내부까지 넘어가게 된다면 관리하기 위한 포인트가 많아진다. 라는 이야기를 재현님이랑 했었는데
이거에 대한 의견도 궁금합니다. (지난번에 `미션 리스트 조회`에서는 의도한대로 null을 넣는게 맞기때문에 Service 레이어에서 null을 넣어주고있음)

2024-01-22 12:44 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/dto/response/FollowMissionFindAllResponse.java
> +    }
아티클 감사합니당!

2024-01-22 13:07 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
> +    }
네 저는 그렇게 이해했는데 기획 확인 해보셔야 할 것 같아요!

현재로선 A유저가 B유저를 팔로우하지 않는다면,
B유저의 정보를 볼 수 있는 페이지가 존재하지 않아서 현재로서는 그럴 것 같아요
(추 후 유저 닉네임 검색 서비스가 생겨서 A유저가 B유저를 팔로우하지 않아도 미션목록 조회가 가능한다고 가정하면, 이때는 A유저가 B유저를 팔로우하지 않았을 때 B유저가 공개여부를 Follow로 올린 미션은 보이지 않는 경우 생김)

2024-01-22 14:11 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/dto/response/MissionFindAllResponse.java
> +    }
차라리 DTO를 하나 더 생성하는 게 나을까용??

2024-01-23 14:13 UTC, kdomo approved these changes
고생하셨슴니당

2024-01-23 15:05 UTC, merged