fix: nickname 검색 예외 처리 (escape)
depromeet/10mm-server pull request #267
Opened 2024-02-01 09:19 UTC by uiurihappy

## 🌱 관련 이슈
- close #266 

## 📌 작업 내용 및 특이사항
**nickname 검색 시 특수문자, 공백에 대한 예외처리**
- 정규식으로 한글, 숫자, 영문 대소문자는 `_`로 replaceAll 처리 후 nativeQuery에서 _로 escaping
- controller에서는 `%` 키워드가 직접 들어올 시 null로 처리하게 되어 NullPointException이 터지는 이슈 해결

## 📝 참고사항
- 디쟌팀과 추가 기획사항이 발생 시 추가 수정 예정

## 📚 기타
- 이렇게 하는 게 맞는 지 본인도 헷갈리니 꼼꼼한 리뷰 바람

2024-02-01 09:27 UTC, kdomo requested changes
정규표현식에 대한 테스트코드만 적어주세용!

2024-02-01 09:27 UTC, kdomo commented on src/main/java/com/depromeet/domain/member/domain/Profile.java
> +    @Pattern(regexp = "[^0-9a-zA-Z가-힣 ]")
message도 함께 넣어주시면 감사하겠습니당

2024-02-01 09:39 UTC, uwoobeat commented
디쟌팀과 닉네임 중간 공백에 대한 정책도 논의해보면 좋을 것 같아요. 나중에 닉네임으로 쿼리 날리는 케이스 생길때 중간에 공백이 있으면 까다로울 것 같아서...!

2024-02-01 09:48 UTC, uiurihappy commented
> 디쟌팀과 닉네임 중간 공백에 대한 정책도 논의해보면 좋을 것 같아요. 나중에 닉네임으로 쿼리 날리는 케이스 생길때 중간에 공백이 있으면 까다로울 것 같아서...!

@uwoobeat 맞아용 그래서 디쟌팀에게 노티드렸구 답변오는대로 또 추가 반영할 예정입니당

2024-02-01 09:49 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/member/domain/Profile.java
> +    @Pattern(regexp = "[^0-9a-zA-Z가-힣 ]")
✅반영 완료✅

2024-02-02 05:37 UTC, kdomo approved these changes
어푸해놓겠습니다 디자인팀과 협의 후 진행해주세요~~!

2024-02-02 05:37 UTC, kdomo commented on src/test/java/com/depromeet/domain/member/application/MemberServiceTest.java
> +                    Member.createNormalMember(Profile.createProfile("도모 바보", "testImageUrl")));
?!

2024-02-02 05:37 UTC, kdomo commented on src/main/java/com/depromeet/domain/member/domain/Profile.java
> +    @Pattern(regexp = "[^0-9a-zA-Z가-힣 ]", message = "올바르지 않는 닉네임 표현입니다.")
```suggestion
    @Pattern(regexp = "[^0-9a-zA-Z가-힣 ]", message = "올바르지 않은 닉네임 표현입니다.")
```

2024-02-02 05:58 UTC, uiurihappy commented on src/test/java/com/depromeet/domain/member/application/MemberServiceTest.java
> +                    Member.createNormalMember(Profile.createProfile("도모 바보", "testImageUrl")));
역시 도모님 꼼꼼하게 이걸 캐치하셨네용..!

2024-02-02 05:58 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/member/domain/Profile.java
> +    @Pattern(regexp = "[^0-9a-zA-Z가-힣 ]", message = "올바르지 않는 닉네임 표현입니다.")
앗 한국어 이슈🥲

2024-02-04 12:03 UTC, merged