feat: 피드 탭 구현
depromeet/10mm-server pull request #277
Opened 2024-02-06 02:27 UTC by uiurihappy

## 🌱 관련 이슈
- close #270 

## 📌 작업 내용 및 특이사항
- 피드 탭 구현 사항으로 엔드포인트는 `/feed/me`, `/feed/{targerId}`로 구현
- `/feed/me`는 탭에 있는 feed 버튼을 클릭 시 동작되는 API
 - member, mission, missionRecord를 join해서 필요한 필드에 대해서만 select하는 방식이기에 Projections 생성자 방식을 사용
 - Projections를 사용을 위한 데이터 모델은 FeedOneResponse로 DTO 클래스 구현
 - Projections를 사용하기에 fetchJoin이 아닌 on절을 사용한 매핑
- `/feed/{targerId}`는 마이프로필과 타인 프로필에 보여지는 피드 API
 - targerId가 본인인 경우 공개 여부 상관없이 전부 조회하고, 아닌 경우 팔로잉 관계에 따라 공개 여부를 결정하여 조회해 response

## 📝 참고사항
![image](https://github.com/depromeet/10mm-server/assets/68099546/2324d1ba-6ecc-49f1-bc77-d89227105c38)
- `/feed/me` API 호출 시 위와 같은 쿼리가 한번 더 발생되는 현상이 있어 같이 고민하면 좋을 듯합니다.

## 📚 기타
-

2024-02-06 02:49 UTC, uiurihappy commented
![image](https://github.com/depromeet/10mm-server/assets/68099546/6cb01617-9622-4be2-a969-91226ef34b05)
+) 해당 위 코드에서 fetchJoin을 하지 않아 발생되는 문제인 듯 해용, 해당 코드에서 memberRelation에 엮여 있는 memberId가 N+1 문제를 일으키는 거 같아, 해당 메서드를 사용하는 API를 테스트 해보고 @kdomo 님께서 문제 없으시면 잠수함 패치로 진행하려 합니당

2024-02-06 10:18 UTC, kdomo requested changes
아직 다 못봤어요.....
집가서 더 볼게용

2024-02-06 10:18 UTC, kdomo commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +        */
요거 프론트랑 상의 되었나용?
자기 자신일 때와 아닐때 둘 다 같은 API를 사용하게 되는데,
저는 팔로잉 팔로워 목록할 때 `/me`와 `/{targerId}`로 나눠달라고 프론트한테 요청받았어서 여쭤봅니당

2024-02-06 10:18 UTC, kdomo commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +        }
```suggestion
        if (!targetId.equals(sourceMember.getId())) {
            return findFeedByTargetMember(sourceMember, targetId);
        }
        return findFeedBySourceMember(sourceMember);
```

요런식으로 Early Return해도 될 것 같네용

2024-02-06 10:18 UTC, kdomo commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +        List<MissionVisibility> visibilities = new ArrayList<>(List.of(MissionVisibility.ALL));
List.of로 생성한 리스트는 Immutable해서 요렇게 쓰신건가용?

그렇다라고 한다면
```suggestion
        List<MissionVisibility> visibilities = new ArrayList<>();
        visiblities.add(MissionVisibility.ALL);
```
도 좋아보이네용

2024-02-06 10:18 UTC, kdomo commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +        }
제가 이해하기로는 
findFeedByTargetMember는 타인 / findFeedBySourceMember는 본인 꺼로 이해했는데
여기 if문에 걸리는 케이스가 있을까요?

2024-02-06 10:18 UTC, kdomo commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +                missionRepository.findFeedAllByMemberId(sourceMember.getId(), null);
findFeedAllByMemberId에 null을 넘기는 것 보단
해당 케이스 경우에 해당하는 visibilities를 채워서 보내준다면 QueryDsl쪽에서 null 체크를 안해도 될거같은데 어떻게 생각하시나유

2024-02-06 10:18 UTC, kdomo commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +                .toList();
flatMap을 쓰신 이유가 궁금합니당,

그리구 missionRecords.stream에서 filter Objects::nonNull은 어떤걸 잡기위해 들어간건가용?
map은 자동으로 있는 값들만 도는걸로 알고있어서 여쭤봅니다잉 👀

2024-02-06 11:04 UTC, uwoobeat requested changes

2024-02-06 11:04 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +        List<MissionVisibility> visibilities = new ArrayList<>(List.of(MissionVisibility.ALL));
별도 메서드로 extract 하는게 좋을 것 같습니다.
ex) `List<MissionVisibility>` 를 리턴하는 `determineVisibilityConditionsByRelationsWithMe`

2024-02-06 11:04 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +    private List<FeedOneByProfileResponse> extractFeedResponses(List<Mission> missions) {
미션기록을 기준으로 쿼리하지 않고 미션을 기준으로 쿼리한 이유가 뭔가요?
다쪽에서 접근하는 게 더 좋을 것 같습니다. 이 방식은 flatMap 연산 비용이 너무 커질 것 같네요

2024-02-07 00:53 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +        }
```
if (!targetId.equals(sourceMember.getId())) {
            return findFeedByTargetMember(sourceMember, targetId);
        }
		return findFeedBySourceMember(sourceMember);
```
위 코드에서 메서드 분리하기 전 작업상태가 아직 남아있었네요 빼도록 하겠습니당

2024-02-07 01:04 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +        */
따로 요청받은 사항은 없었고, 마이프로필, 타인의 프로필에서 같은 Response값을 내려주기에 이렇게 구현했었습니당

2024-02-07 01:27 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +                .toList();
기존 missionRepository에서 record 데이터를 조회를 해와서 flatMap을 사용했었습니다.
그런데 아래 재현님이 작성한 코멘트에 `다`(missionRecord)를 기준으로 조회를 하면 map을 사용할 수 있어 그렇게 수정하도록 하겠습니도

2024-02-07 01:44 UTC, kdomo requested changes

2024-02-07 01:44 UTC, kdomo commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +                        sourceId, targetMember.getId());
요거 반대로 되야하지 않나용?

B유저가 미션을 FOLLOW에게만 공개를 해놓은 상태에서,
A유저(로그인된유저)가 B유저를 조회할 때, B유저가 A를 팔로우했는지를 체크해야 할 것 같은데
그 반대로 되고있는거같아서 여쭤봄니당

2024-02-07 02:04 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +                        sourceId, targetMember.getId());
B유저가 A를 팔로워해야 FOLLOWER 관계가 성립되나용??
저는 저번 친구 미션 목록을 조회했을 때랑 같은 공개여부 조건으로 인지하고 있었습니다!

한번 디쟌팀과 의논해보겠습니당

2024-02-07 02:13 UTC, kdomo commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +                        sourceId, targetMember.getId());
A가 B 유저를 조회할 때, B가 A를 팔로우하고있어야 팔로우공개인 미션이 보이는게 아닌가용?

2024-02-07 02:14 UTC, kdomo commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +                        sourceId, targetMember.getId());
요거 그때 나왔던거랑 비슷한 이야기 같은데 디자인팀과 논의 후 공유해주시면 감사하겠습니당

2024-02-07 02:23 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +                        sourceId, targetMember.getId());
![image](https://github.com/depromeet/10mm-server/assets/68099546/fc497e4a-8f36-4066-a42e-7115a0cff97a)

당시 친구 미션 목록 조회했을 때 이 조건을 사용했어서 피드쪽에 대한 공개여부는 별도인지 한번 논의해볼게용

2024-02-07 04:20 UTC, kdomo approved these changes
어푸 해놓을게용 요것만 처리부탁드립니당,
재현님한테도 어푸 받고 머지해주세용

2024-02-07 04:20 UTC, kdomo commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +@RequiredArgsConstructor
`@Transactional` 빠져있어용

2024-02-07 04:20 UTC, kdomo commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +    public List<FeedOneByProfileResponse> findAllFeedByTargetId(Long targetId) {
`@Transactional(readOnly = true` 빠져있어용

2024-02-07 04:35 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +    private List<FeedOneByProfileResponse> extractFeedResponses(List<Mission> missions) {
말씀하신대로 다쪽에서 접근하여, flatMep이 아닌 map으로 연산하게끔 수정했어용
리뷰 감사합니당

2024-02-07 05:50 UTC, uwoobeat requested changes

2024-02-07 05:50 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +                        determineVisibilityConditionsByRelationsWithMe(
`determine...Me()`는 복잡한 로직이니, 변수로 extract 하여 인자로 넘기는게 좋습니다.
> Do one thing in one line!

2024-02-07 05:50 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +                .map(record -> FeedOneByProfileResponse.of(record.getMission(), record))
```suggestion
                .map(FeedOneByProfileResponse::of)
```

메서드 참조를 사용해보세용
of 로직 내부에서 `record.getMission()`을 호출하면 됩니다

2024-02-07 05:50 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +        if (!isMyFeedRequired(targetId, sourceId)) {
```suggestion
        if (isMyFeedRequired(targetId, sourceId)) {
```
로 수정하고 순서 바꾸는게 더 좋을 것 같아요

2024-02-07 07:38 UTC, uwoobeat approved these changes
어푸푸루푸루부

고생하셨어용

2024-02-07 07:43 UTC, merged