feat: 피드 페이지네이션 구현
depromeet/10mm-server pull request #362
Opened 2024-03-10 09:03 UTC by uiurihappy

## 🌱 관련 이슈
- close #361 

## 📌 작업 내용 및 특이사항
- 피드 페이지네이션 구현
- Slice를 활용하여 size, lastId를 QueryString으로 받아 no-offset 방식을 사용

## 📝 참고사항
- https://forkyy.tistory.com/84
- https://green-bin.tistory.com/23

## 📚 기타
-

2024-03-12 11:31 UTC, uwoobeat requested changes

2024-03-12 11:31 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +    public FeedSliceResponse findFeedByPage(int size, Long lastId, MissionVisibility visibility) {
지금 보아하니 하나의 서비스 코드로 묶을 필요가 없다고 생각하는데 어떻게 보시나요?
공개여부에 따라서 완전히 다른 두 로직을 처리하고 있어서, 분리하는게 낫지 않을까 싶습니다

2024-03-13 09:17 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +    public FeedSliceResponse findFeedByPage(int size, Long lastId, MissionVisibility visibility) {
공개여부에 따른 서비스 코드 분리라 하면, controller에서 공개여부 분기 처리를 하고 호출하는 방식으로 바꾸면 될까용??

2024-03-15 07:18 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/feed/application/FeedService.java
> +    public FeedSliceResponse findFeedByPage(int size, Long lastId, MissionVisibility visibility) {
아뇹. 분기 자체는 서비스 레이어에서 치고, 각 분기에서 호출하는 메서드를 분리하자는 이야기였어요
컨트롤러에서 A를 호출하고, 분기에 따라 내부적으로 A1과 A2를 호출 << 이렇게요

2024-03-15 07:23 UTC, uwoobeat approved these changes
선어푸할게요
전반적으로 메서드 네이밍에 컨텍스트가 담겨있지가 않아서 이게 어디서 어떻게 사용되는지 파악하기가 어려운 것 같습니다. 메서드 네이밍에 컨텍스트가 담기면 좋겠지만 그러기가 어렵다면 주석이라도 적어주시면 좋을 것 같아요

2024-03-15 07:23 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/feed/api/FeedController.java
> +            return feedService.findFeedByPageForAllVisibility(size, lastId);
```suggestion
            return feedService.findAllFeed(size, lastId);
```

2024-03-15 07:23 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/feed/api/FeedController.java
> +            return feedService.findFeedByPageForCurrentVisibility(size, lastId);
```suggestion
            return feedService.findFollowerFeed(size, lastId);
```

2024-03-15 08:41 UTC, merged