feat: 미션 리마인드 알림 시간 설정 및 시간에 따른 푸시 알림 전송
depromeet/10mm-server pull request #371
Opened 2024-03-22 07:33 UTC by uiurihappy

## 🌱 관련 이슈
- close #363 

## 📌 작업 내용 및 특이사항
- 미션 시작 리마인드 알림시간 설정을 위한 mission 엔티티에 remindedTime(nullable) 추가
- 생성, 수정 시 remindedTime LocalTime 필드 추가 Request하도록 구현
- Scheduler에서 매 10분마다 In-progress인 미션 대상으로 전체 조회
- 조회 후 현재 now의 LocalTime과 설정한 미션 리마인드 시간 LocalTime과 동일한 지 체크
- 체크 후 대상 미션에 대하여 fcmToken을 List화 하여 전체 푸시 알림 전송

## 📝 참고사항
- 

## 📚 기타
-

2024-03-24 10:04 UTC, uwoobeat requested changes

2024-03-24 10:04 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    private LocalTime remindedTime;
현재 컨벤션 상으로는 시간을 나타내기 위해`xxxAt` 을 사용하고 있으므로 `remindedTime` 은 적절하지 않을 것 같습니다.

그리고 앞으로 리마인드 해줘야 할 시간을 나타내기 때문에 과거형으로 `reminded` 를 쓰는 것도 어색한 것 같네요.

`remindAt` 이 가장 적절한 표현이 되지 않을까 싶습니다.

2024-03-24 10:14 UTC, uwoobeat requested changes

2024-03-24 10:14 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
> +    List<Mission> findAllInProgressMission();
QueryDSL을 사용하신 이유가 있나요?
Spring Data JPA 쿼리 메서드를 사용해도 될 것 같습니다.

2024-03-24 10:14 UTC, uwoobeat commented on src/main/java/com/depromeet/scheduler/mission/MissionBatchScheduler.java
> +        LocalDateTime now = LocalDateTime.now();
`LocalTime.now()` 를 사용하면 더 간결할 것 같습니다.

2024-03-24 10:14 UTC, uwoobeat commented on src/main/java/com/depromeet/scheduler/mission/MissionBatchScheduler.java
> +        findFcmTokensForRemindPush(currentTime, inProgressMissions);
메서드 이름과 실제 동작이 일치하지 않습니다.
메서드 이름에 따르면 리마인드 푸시를 위해 Fcm 토큰 리스트를 찾을 것으로 기대되는데 실제 리턴타입은 void입니다.

또, currentTime을 외부에서 주입할 필요가 없을 것 같네요.

2024-03-24 11:08 UTC, kdomo approved these changes
재현님이 말씀해주신것 외에는 다 좋아보입니당
저는 선 어푸하겠슴니다

+ 테스트에 미션 의존되는게 많네요ㅜㅜ

2024-03-24 14:14 UTC, uwoobeat requested changes

2024-03-24 14:14 UTC, uwoobeat commented on src/main/java/com/depromeet/scheduler/mission/MissionBatchScheduler.java
> +            LocalTime currentTime, List<MissionRemindPushResponse> inProgressMissions) {
항상 현재 시간이 인자로 들어오는 것이라면 내부에서 LocalTime.now를 호출해도 될 것 같습니다.

2024-03-25 06:35 UTC, uwoobeat requested changes

2024-03-25 06:35 UTC, uwoobeat commented on src/main/java/com/depromeet/scheduler/mission/MissionBatchScheduler.java
> +                LocalTime.parse(LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm")));
`LocalTime.now()` 이 아니라 파싱하고 포맷팅하는 과정이 들어간 이유가 궁금합니다~

2024-03-25 06:35 UTC, uwoobeat commented on src/main/java/com/depromeet/scheduler/mission/MissionBatchScheduler.java
> +    private void sendFcmTokensForRemindPush(List<MissionRemindPushResponse> inProgressMissions) {
리스트를 받아서 내부적으로 스트림을 돌지 말고
외부에서 스트림을 돌게 하고 내부 동작 `mission -> fcmService.sendMessageSync(...)` 을 메서드로 추출해서 forEach에 메서드 레퍼런스로 넘기는 쪽이 더 깔끔할 것 같네요

2024-03-25 08:24 UTC, uiurihappy commented on src/main/java/com/depromeet/scheduler/mission/MissionBatchScheduler.java
> +                LocalTime.parse(LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm")));
파싱한 이유는
![image](https://github.com/depromeet/10mm-server/assets/68099546/3d471b48-0729-4ea6-9064-e46ce12db2ad)
이와 같이 LocalTime.now()로 했을 때 ms 단위까지 나오는 현상이 있어서 equals를 하였을 경우, false로 떨어지는 현상이 있기 때문에 파싱하고 포맷팅하는 과정을 넣었습니다.

혹시 보다 나은 방법이 있을까요??

2024-03-25 11:54 UTC, uwoobeat commented on src/main/java/com/depromeet/scheduler/mission/MissionBatchScheduler.java
> +                LocalTime.parse(LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm")));
`truncateTo()`를 사용하면 될 것 같네요

2024-03-25 12:56 UTC, uwoobeat approved these changes
lgtm

2024-03-25 13:44 UTC, merged