chore: 코드 정적 분석 SonarCloud 설정
depromeet/10mm-server pull request #38
Opened 2023-12-01 12:55 UTC by uiurihappy

## 🌱 관련 이슈
<p> # 뒤에 이슈 번호를 작성해주세요. <p>

- close #11 

---
## 📌 작업 내용 및 특이사항
- sonarCloud 정적 분석 도구 설정
- [10mm sonarCloud 페이지](https://sonarcloud.io/project/overview?id=depromeet_10mm-server)
- `property 'sonar.coverage.jacoco.xmlReportPaths', 'build/reports/jacoco/index.xml'` 이 코드에서 jacoco의 결과물 xml 파일을 읽어 코드 커버리지 분석

---
## 📝 참고사항
- [설정 참고 링크1](https://velog.io/@chaerim1001/Springboot-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-SonarCloud%EB%A1%9C-%EC%A0%95%EC%A0%81-%EC%BD%94%EB%93%9C-%EB%B6%84%EC%84%9D%ED%95%98%EA%B8%B0-with-github-actions)
- [설정 참고 링크2](https://gong-check.github.io/dev-blog/BE/%EC%98%A4%EB%A6%AC/sonarcloud/sonarcloud/)

--- 
## 📚 기타
- You are running CI analysis while Automatic Analysis is enabled. Please consider disabling one or the other. 에러로 CI분석 또는 자동분석으로 둘중 하나만 실행되게끔 수정해야함 `수정완료`

2023-12-04 14:47 UTC, kdomo approved these changes
고생하셨슴니당

2023-12-05 01:52 UTC, uiurihappy commented
@uwoobeat 
build-action에서 통합하여 SONAR_TOKEN을 환경변수로 등록하여 실행시도 해봤지만, projectKey와 같이 프로퍼티를 읽어오지 못해서 기존 빌드 성공했던 방식으로 해야할 거 같습니다.

2023-12-05 06:31 UTC, uwoobeat requested changes
지금 check가 두번씩 돌아가는데 체크좀 부탁드려요

<img width="761" alt="image" src="https://github.com/depromeet/10mm-server/assets/91878695/f99d4463-51d8-4e62-a8b2-210414819493">

2023-12-05 07:20 UTC, uiurihappy commented
> 지금 check가 두번씩 돌아가는데 체크좀 부탁드려요
> 
> <img alt="image" width="761" src="https://private-user-images.githubusercontent.com/91878695/287944537-f99d4463-51d8-4e62-a8b2-210414819493.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjExMDQsIm5iZiI6MTcwMTc2MDgwNCwicGF0aCI6Ii85MTg3ODY5NS8yODc5NDQ1MzctZjk5ZDQ0NjMtNTFkOC00ZTYyLWE4YjItMjEwNDE0ODE5NDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA3MjAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZmZiMmE4OGJjZmE2NjQyZDU5MzA3MzIyMDRjNDlhMmRhYjcyYzE5MzllZjEyNzMzYTA5NDBkNmI3ZDQ2ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ovct1u-Pie9lR0e4CxaVZYK9IBBEYzy2ewjTik6aL3I">

@uwoobeat 
수정완료했습니다!

2023-12-05 08:57 UTC, uwoobeat approved these changes
lgtm

gradle build에 sonar + jacoco 디펜던시를 추가 가능한지 검증하는 이슈만 추가해주시면 나중에 저도 한번 테스트해볼게요~

2023-12-05 09:08 UTC, merged