test: Database cleaner JUnit extension으로 변환
depromeet/10mm-server pull request #389
Opened 2024-04-27 02:42 UTC by uiurihappy

## 🌱 관련 이슈
- close #388 

## 📌 작업 내용 및 특이사항
- 1. JUnit의 Extension 활용
- 2. Auto Detection

## 📝 참고사항
- [@Transactional 없애려다 오픈소스 라이브러리까지 만든 이야기](https://blog.ban-life.com/transactional-%EC%97%86%EC%95%A0%EB%A0%A4%EB%8B%A4-%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC%EA%B9%8C%EC%A7%80-%EB%A7%8C%EB%93%A0-%EC%9D%B4%EC%95%BC%EA%B8%B0-5426116036bb)
- [JUnit 5 extension](https://www.baeldung.com/junit-5-extensions)

## 📚 기타
-

2024-04-28 05:55 UTC, uwoobeat requested changes

2024-04-28 05:55 UTC, uwoobeat commented on src/test/java/com/depromeet/DatabaseCleaner.java
> +public abstract class DatabaseCleaner {
유틸리티 클래스의 인스턴스화를 막기 위해서는 추상 클래스보다 private 생성자를 사용하는 것이 좋습니다.

https://limdingdong.tistory.com/19

2024-04-29 04:49 UTC, uwoobeat commented on src/test/java/com/depromeet/NoTransactionExtension.java
> +        // validateTransactionalAnnotationExists(extensionContext);
여기는 사용 안하는 건가요?

2024-04-29 05:37 UTC, uiurihappy commented on src/test/java/com/depromeet/NoTransactionExtension.java
> +        // validateTransactionalAnnotationExists(extensionContext);
@uwoobeat 사용하려 했으나 MissionRepository 테스트 내에서는 `@Transaction`이 걸려있지 않고, Repository 테스트 시 Assertions이 걸려서 지금 알아보고 있는 중임다

2024-04-29 08:05 UTC, uwoobeat commented on src/test/java/com/depromeet/NoTransactionExtension.java
> +        // validateTransactionalAnnotationExists(extensionContext);
음 굳이 JUnit Extension으로 해결하지 않아도 괜찮지 않을까요?

https://github.com/GDSC-Hongik/gdsc-server/pull/268

요건 제가 딴 플젝에서 세팅한 통합 테스트 템플릿인데요, 여기서는 각각의 통합 테스트 클래스가 `IntegrationTest` 를 상속받도록 하고,  템플릿 내에서 `@BeforeEach` 에서 클리너를 명시적으로 호출하는 방식으로 해결했어요.

개인적으로는 auto detection 방식이 과도하게 로직을 감추고 있어서 내부 동작을 이해하기 어렵게 만드는 것 같다는 생각이 드네요

2024-06-14 07:05 UTC, uwoobeat approved these changes
lgtm

2024-06-14 07:15 UTC, kdomo approved these changes
LGTM

2024-06-16 13:20 UTC, merged