feat: 랭킹 API 구현
depromeet/10mm-server pull request #391
Opened 2024-05-06 07:44 UTC by uiurihappy

## 🌱 관련 이슈
- close #390 

## 📌 작업 내용 및 특이사항
- 랭킹 갱신을 위해 member 테이블보다는 ranking 테이블을 생성하여 활용도를 올리는 방향으로 선택
- 랭킹 갱신 시간은 21시로, 초기 랭킹 데이터 생성과 갱신을 위해 insert duplicate Native-Query를 활용

## 📝 참고사항
- 

## 📚 기타
-

2024-05-08 14:34 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/ranking/application/RankingService.java
> +    }
해당 메서드는 SymbolStack을 약속한 시간에 갱신하기 위한 메서드이며 스케줄러에서만 사용되는 메서드입니당
rankingDtos는 findAllMissionSymbolStack 메서드로 인한 멤버 별 SymbolStack을 구한 List DTO로 해당 데이터를 갱신하고 있어요

좀 더 명확하게는 duplicate라고 메서드 명을 수정하는 게 낫겟네용👍

update를 할때 NOW()를 실행한 것을 보실때 쿼리가
```java
@Query(
            value =
                    "INSERT INTO Ranking (member_id, symbol_stack, created_at) "
                            + "VALUES (:memberId, :symbolStack, NOW()) "
                            + "ON DUPLICATE KEY UPDATE member_id = :memberId, symbol_stack = :symbolStack, updated_at = NOW()",
            nativeQuery = true)
```
이처럼 insert 시 created_at에만 NOW(), update 시에는 updated_at에만 NOW() 실행하도록 하고 있어용
`동일한 시간으로 판단되어서 중복으로 보는지`에 대한 의미에 대해 다시 알 수 있을까요??

2024-05-08 14:35 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/ranking/dao/RankingRepository.java
> +                            + "ON DUPLICATE KEY UPDATE member_id = :memberId, symbol_stack = :symbolStack, updated_at = NOW()",
넵 데이터가 있을때만 업데이트되어 업데이트 시간만을 NOW()로 갱신해줍니당

2024-05-09 14:18 UTC, kdomo commented
아 제가 로직을 잘못이해하고 있었군요,
윤범님이 짜신 로직이
첫째날, 21시에 랭킹테이블에 최초 1회 데이터 생성
둘째날, 21시에 기존에 있는 데이터에 심볼스택과, updatedAt을 업데이트
이거군요,

저는 날짜별로 랭킹에 대한 정보를 남겨놔야된다고 생각하고 있었어서,
업데이트를 왜 하는거지? 라는 의문이 있어서 질문 남겼던거였어용(머쓱)

기획상 필요하지 않을지 모르겠지만 윤범님이 구현하신 대로라면,
특정 과거일자에 랭킹에 들었던 유저를 찾고 싶다면 어떻게 해야할까요?

2024-05-09 14:23 UTC, kdomo commented
> @kdomo 사실 이 부분을 개발하면서 약간 걸렸던게 21시에 스케줄 실행 시 duplicate 쿼리문이 symbolStack이 있는 멤버 수만큼 실행되서 혹시나 쿼리 수 감소나 성능을 최적화할 방법이 있을까요?.?

미션레코드에 존재하는 duration값으로 simbolStack을 계산하고 있으니, 지금 설계대로라면 딱히 방법이 떠오르진 않는군요,
우선 데이터가 그렇게 많지 않아서 문제가 발생할 것 같진 않아보이는데,
스케줄이 동작하는 시간(21시)에 서버 지표를 좀 확인해봐야할 것 같아용
만약 서버 인스턴스에 부하가 걸린다면 스케줄을 분리하는 쪽도 고려해 볼 수 있을 것 같네욤

+ 랭킹 데이터가 21시에 업데이트되고, 변하지 않는 값이니 24시간 동안 캐싱 되어도 좋을 것 같아용
회의때 논의해보시죠 😆

2024-05-11 11:03 UTC, uwoobeat requested changes
테스트도 같이 작성해주시면 좋을듯 합니다

2024-05-11 11:27 UTC, uwoobeat requested changes

2024-05-11 11:27 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/ranking/dao/RankingRepositoryCustom.java
> +    void saveOrUpdate(Ranking ranking);
RepositoryCustom은 QueryDSL 기능을 사용하기 위한 목적을 가지는 것이 아닌가요?
왜 saveAndUpdate가 들어갔는지 궁금합니다.

2024-05-11 11:27 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/ranking/dto/response/RankingResponse.java
> +        @Schema(description = "랭킹", defaultValue = "1") long rank,
멤버 ID에서는 Long을 사용하고, 랭크 및 기타 필드에서는 long을 사용하신 이유가 있나요?

2024-05-19 08:40 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/ranking/dao/RankingRepositoryCustom.java
> +    void saveOrUpdate(Ranking ranking);
미사용 메서드입니당
이전 랭킹 데이터를 효율적으로 저장하는 것에 대해 고민하다 그대로 두었네용😅

2024-05-19 08:42 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/ranking/dto/response/RankingResponse.java
> +        @Schema(description = "랭킹", defaultValue = "1") long rank,
현재 memberId는 일관성 있게 Long으로 사용하였고,
long을 사용하는 이유는 굳이 기타 필드에 참조 타입 Long을 사용할 필요가 없다고 생각했어용
만약 rank나 symbolStack이 int의 범위만으로 충분하다면 int로 바꾸는 것도 고려할만하겠네요!

2024-05-19 08:47 UTC, uiurihappy commented
@kdomo

> 특정 과거일자에 랭킹에 들었던 유저를 찾고 싶다면 어떻게 해야할까요?
 
저도 기획상 필요성에 대해 느껴지지 않지만, 만약 필요하다면
특정 과거일자의 사용자 랭킹을 찾는다면 아마 save로만 진행하여 일자별 데이터를 저장하도록 해야할 듯해용

2024-06-14 07:06 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/ranking/dto/response/RankingResponse.java
> +        @Schema(description = "랭킹", defaultValue = "1") long rank,
음 그래도 박싱 / 언박싱 비용 생각해서 일관성 있게 전부 참조타입으로 맞춰주는게좋지 않을까 싶네요
이거는 선택적으로 적용하시면 될듯 합니다

2024-06-14 07:07 UTC, uwoobeat approved these changes
lgtm

2024-06-15 04:50 UTC, kdomo approved these changes
LGTM

2024-06-15 10:08 UTC, merged