Java 21
depromeet/10mm-server pull request #420
Opened 2024-12-10 11:34 UTC by char-yb

## 🌱 관련 이슈
- close #419 

## 📌 작업 내용 및 특이사항
- Java 21으로 변경
- yml에 Virtual Thread 사용하도록 옵션 추가
- 21 사용에 따라 Spring boot ver 3.4.0으로 migration
- gradle version 8.10으로 변경
- Jacoco version도 gradle 8.10 변경으로 인해 0.8.12로 변경
- Spotless 6.21.0으로 변경

## 📝 참고사항
- 3.4.0으로 변경 중 test 코드에서 MockBean 어노테이션이 Deprecated 됨으로 MockitoBean 사용

## 📚 기타
-

2024-12-10 12:11 UTC, uwoobeat approved these changes
굿이에요
추가로 Generational ZGC 키워드로도 찾아보시겠어요?
Java 21 도입한다면 검토해볼만한 부분이라고 봅니다.

2024-12-10 12:19 UTC, uwoobeat requested changes

2024-12-10 12:19 UTC, uwoobeat commented on Dockerfile
> +FROM eclipse-temurin:21
그리고 저희 aws로 이전하고 나서 os로 al2023을 사용하고 있으니, amazon corretto jdk를 사용하는데 더 좋을 것 같아요.
++ 이미지 크기도 줄일 겸 alpine으로 변경하면 더 좋고요.

> ✅ Recommendation: Corretto builds are a good choice, particularly if you run Java applications directly on Amazon Linux 2 in AWS. [레퍼런스](https://whichjdk.com/)

2024-12-10 12:24 UTC, char-yb commented on Dockerfile
> +FROM eclipse-temurin:21
동의합니당👍
corretto jdk 버전 확인 후 적용해볼게용

2024-12-11 10:50 UTC, uwoobeat approved these changes
lgtm

2024-12-11 10:52 UTC, merged