Feature/44 spring enviroment helper
depromeet/10mm-server pull request #45
Opened 2023-12-05 09:08 UTC by kdomo

## 🌱 관련 이슈
- close #44 

## 📌 작업 내용 및 특이사항
- 작성중

## 📝 참고사항
- 

## 📚 기타
-

2023-12-11 15:07 UTC, uiurihappy approved these changes
LGTM

2023-12-11 17:21 UTC, uwoobeat requested changes

2023-12-11 17:21 UTC, uwoobeat commented on src/main/java/com/depromeet/global/util/SpringEnvironmentHelper.java
> +        String[] activeProfiles = environment.getActiveProfiles();
하나의 stream 로직으로 개선할 수 있을 것 같습니다.

```java
public Boolean isProdProfile() {
    return Arrays.stream(environment.getActiveProfiles())
                 .anyMatch(PROD::equals);
}
```

2023-12-11 17:21 UTC, uwoobeat commented on src/main/java/com/depromeet/global/util/SpringEnvironmentHelper.java
> +    public String getCurrentProfile() {
isProdProfile과 isDevProfile은 각각의 스트림을 호출하므로 하나의 스트림만 호출하도록 최적화할 수 있을 것 같습니다.
```java
public String getCurrentProfile() {
    // Stream<String> activeProfiles = Arrays.stream(environment.getActiveProfiles()) 
    // getActiveProfile은 중복해서 호출하므로 따로 private method로 빼주는 게 좋을듯
    return getActiveProfiles
                         .filter(profile -> profile.equals(PROD) || profile.equals(DEV))
                         .findFirst()
                         .orElse(LOCAL);
}
```

2023-12-11 17:21 UTC, uwoobeat commented on src/test/java/com/depromeet/global/util/SpringEnvironmentHelperTest.java
> +    private final String PROD = "prod";
서로 다른 "prod" 문자열 상수가 프로덕션과 테스트 코드에 중복되어 존재하므로 Helper의 문자열 상수를 public으로 열고 재할당하거나 직접 사용하는 것이 좋을 것 같습니다~

2023-12-12 10:12 UTC, kdomo commented
@uwoobeat 수정 완료😉

2023-12-12 10:34 UTC, uwoobeat requested changes

2023-12-12 10:34 UTC, uwoobeat commented on src/main/java/com/depromeet/global/config/security/WebSecurityConfig.java
> +@AllArgsConstructor
사소한 거긴 한데 `@RequiredArgsConstructor`를 사용하는 편이 DI라는 컨텍스트를 더 잘 전달할 수 있을 것 같아요~

2023-12-12 10:34 UTC, uwoobeat commented on src/main/java/com/depromeet/global/util/SpringEnvironmentUtil.java
> +    public static String DEV = "dev";
DEV, LOCAL 상수도 final 사용하여 불변으로 만들어주면 좋을 것 같습니다

2023-12-12 10:34 UTC, uwoobeat commented on src/test/java/com/depromeet/global/util/SpringEnvironmentUtilTest.java
> +    void 상용_환경이라면_isProdProfile은_true를_반환한다() {
test convention도 이야기를 해봐야 할 것 같습니다~

만약 메서드 이름을 영어로 따로 지어준다면 (e.g `void shoudReturnTrueWhenIsProdProfile`)
 `@DisplayName` 을 한글로 지어주는 것이 맞을 것 같고
그렇지 않다면 중복 없이 DisplayName 없이 그냥 snake case로만 설명을 걸어주는 게 좋을 것 같은데 어떤 쪽이 더 좋을까요?

++ 언더바 들어간게 가독성이 그렇게 안 좋은 것도 아니라서 굳이 중복해서 DisplayName을 붙여줄 필요는 없지 않나 생각합니다

2023-12-12 10:34 UTC, uwoobeat commented on src/test/java/com/depromeet/global/util/SpringEnvironmentUtilTest.java
> +import static org.mockito.BDDMockito.*;
Mockito가 아니라 BDDMockito를 사용하신 이유가 궁금합니다~

2023-12-12 10:34 UTC, uwoobeat commented on src/test/java/com/depromeet/global/util/SpringEnvironmentUtilTest.java
> +        given(environment.getActiveProfiles()).willReturn(new String[] {PROD});
stubbing으로 string 배열 리턴하는 부분에서 문자열 배열도 상수로 빼줘서 관리하면 어떨까 싶습니다. (`PROD_ARRAY` 같이요)

2023-12-12 10:34 UTC, uwoobeat commented on src/main/java/com/depromeet/global/config/security/WebSecurityConfig.java
> +            configuration.addAllowedOriginPattern("http://localhost:5173");
저번에 프론트쪽에 물어봤는데 vite 안써서 3000만 열어주면 된다고 합니다 ㅎㅎ

2023-12-12 10:40 UTC, kdomo commented on src/main/java/com/depromeet/global/util/SpringEnvironmentUtil.java
> +    public static String DEV = "dev";
와 요거 놓쳤네요 감사합니다

2023-12-12 10:44 UTC, kdomo commented on src/test/java/com/depromeet/global/util/SpringEnvironmentUtilTest.java
> +    void 상용_환경이라면_isProdProfile은_true를_반환한다() {
``
++ 언더바 들어간게 가독성이 그렇게 안 좋은 것도 아니라서 굳이 중복해서 DisplayName을 붙여줄 필요는 없지 않나 생각합니다
``
DisplayName 제거하는쪽이 더 좋을 것 같군요!

2023-12-12 10:45 UTC, kdomo commented on src/test/java/com/depromeet/global/util/SpringEnvironmentUtilTest.java
> +import static org.mockito.BDDMockito.*;
저는 보통 given when then으로 테스트코드를 작성하는데,
Mockito는 when으로 스터빙하여 가독성이 좋지 않아서 BDDMockito를 사용했습니다!

2023-12-12 11:11 UTC, uiurihappy commented on src/test/java/com/depromeet/global/util/SpringEnvironmentUtilTest.java
> +    void 상용_환경이라면_isProdProfile은_true를_반환한다() {
저도 둘중엔 DisplayName 제거하는 쪽이 더 좋을 거 같다 생각합니다

2023-12-12 11:54 UTC, uwoobeat approved these changes
LGTM

2023-12-13 12:38 UTC, merged