Feature/54 mission domain
depromeet/10mm-server pull request #60
Opened 2023-12-13 06:43 UTC by uiurihappy

## 🌱 관련 이슈
- close #54 

## 📌 작업 내용 및 특이사항
- 미션/미션 기록 도메인 엔티티 생성
- 생성한 도메인 Test 코드 작성
- 회원 도메인과 동일하게 내부에서는 빌더 / 외부에서는 정적 팩토리 메서드를 사용하게 구현

## 📝 참고사항
- DAO 내 MemberRepository에서 @Repository 어노테이션도 추가했습니다.

## 📚 기타
-

2023-12-14 09:56 UTC, uwoobeat requested changes
수고하셨습니다.

2023-12-14 09:56 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/member/dao/MemberRepository.java
> +@Repository
Spring Data Jpa 사용 시 `@Repository` 어노테이션은 추가하지 않아도 됩니다.

https://stackoverflow.com/questions/44069367/repository-not-necessary-when-implementing-jparepository

2023-12-14 09:56 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +                .category(MissionCategory.ETC)
카테고리의 경우 미션 생성할 때 사용자한테서 받아야 하는 값이므로 파라미터로 받아줘야 할 것 같습니다.

2023-12-14 09:56 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +                .sort(1)
sort 디폴트값을 지정하게 되면 중복 sort 값이 발생하기 때문에 인자값을 받거나 / null로 두고 추후 순서 결정 로직을 통해 확정시키는 게 좋을 것 같습니다.

2023-12-14 09:56 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +                .visibility(MissionVisibility.PUBLIC)
미션 생성시 공개/비공개 여부를 받으므로 파라미터로 받아줘야 합니다.

2023-12-14 09:56 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    @Column(columnDefinition = "varchar(50) not null")
미션 이름 길이 같은 정책은 아직 확정이 되지 않아서 아젠다에 추가해놓고 논의하는게 좋을 것 같습니다
프론트 입장에서도 고려를 해야 하는 부분이라서요

2023-12-14 09:56 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    @Column(columnDefinition = "varchar(50) not null")
그리고 `not null`의 경우 `@Column(nullable = false)` 와 같이 대체할 수 있습니다.

2023-12-14 09:56 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    @Lob
Lob을 쓰신 이유가 있나요?

2023-12-14 09:56 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    @Column(columnDefinition = "int not null default '1'", name = "sort")
디폴트 값 정책은 디비단보다 애플리케이션 단에서 관리하는 편이 더 좋을 것 같습니다

2023-12-14 09:56 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    public static Mission registerPublicMission(String name, String content, Member member) {
컨벤션에 맞게 접두사로 create로 변경해주면 어떨까요?

2023-12-14 09:56 UTC, uwoobeat commented on src/test/java/com/depromeet/domain/mission/domain/MissionTest.java
> +        member = Member.createNormalMember(profile);
일반적으로 멤버 선언 시 static으로 사용하지 않을 거라서, 동일하게 인스턴스 멤버로 픽스처 선언해주면 좋을 것 같습니다.

2023-12-14 09:56 UTC, uwoobeat commented on src/test/java/com/depromeet/domain/missionRecord/domain/MissionRecordTest.java
> +                        duration, "testMissionRecord_remark", startedAt, finishedAt, mission);
변수명에 언더스코어(`_`) 사용하는 것은 자바 네이밍 컨벤션이 아니니 카멜케이스로 통일해주면 좋을 것 같습니다.

2023-12-14 09:56 UTC, uwoobeat commented on src/test/java/com/depromeet/domain/missionRecord/domain/MissionRecordTest.java
> +        LocalDateTime startedAt = LocalDateTime.now();
테스트에서는 `LocalDateTime.now()`를 지양하는 것이 좋습니다.

테스트마다 매번 달라지는 값을 넣게 되면 테스트 멱등성을 위반하기 때문에 비즈니스 로직과 관계된 부분이 아니라면 되도록 고정된 값 (`LocalDateTIme.of(...)`)를 사용해야 합니다!

2023-12-14 09:56 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    @OneToMany(mappedBy = "mission", cascade = CascadeType.ALL)
쿼리 대부분이 미션에서 미션기록으로 접근할 것 같으니 orphanRemoval 옵션까지 걸어주면 좋을 것 같습니다

2023-12-14 09:56 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
> +    @Column(columnDefinition = "text not null COMMENT '미션 일지'")
위와 동일하게 코멘트 어노테이션으로 분리하는 쪽이 좋을 것 같습니다.

2023-12-14 09:56 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
> +    @Column private Integer duration;
불필요한 `@Column` 은 제거해주면 될 것 같습니다.

2023-12-14 09:56 UTC, uwoobeat commented on .github/workflows/develop_pull_request.yml
> +        run: ./gradlew sonar --info --stacktrace --no-daemon
왜 데몬으로 실행하지 않는지 설명해주실 수 있나요?

2023-12-14 10:25 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +                .category(MissionCategory.ETC)
아 그렇네요 수정해두겠습니다!

2023-12-14 10:27 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +                .visibility(MissionVisibility.PUBLIC)
넵넵 이 부분도 수정해두겠습니다!

2023-12-14 10:39 UTC, uiurihappy commented on .github/workflows/develop_pull_request.yml
> +        run: ./gradlew sonar --info --stacktrace --no-daemon
저 옵션은 지금 SonarCloud report가 계속 pending으로 떨어지고 있어서
commit 올릴 시 Action을 다시 실행하려고 했던 것이였습니다
나중에 원복할 계획입니다!

2023-12-14 11:45 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +                .sort(1)
'최근에 생성한 미션 기록은 최상단에 위치한다'와 같은 기획이 있다면 비지니스 로직이 더 쉬워지겠네용
이 부분도 같이 이야기해보아용

2023-12-14 15:55 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    @Lob
Lob은 보통 큰 데이터 타입을 지정하기 위해 사용하는데 
varchar는 일반적으로 255까지밖에 길이를 제공하지 않기에 text 타입으로 지정하고자 Lob을 사용했습니다. `미션 내용`같은 경우 255자가 넘어갈 수도 있지 않을까라는 생각에 추가했습니다.

2023-12-22 08:15 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    @Column(columnDefinition = "text", nullable = false)
`columnDefinition = "text"`이 왜 필요한지 설명해주실 수 있나용 ??

2023-12-22 08:15 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    @Column(name = "sort", nullable = false)
`name = "sort"`값을 지정안해주어도 필드명에 따라 자동으로 sort로 들어가지 않나요??

2023-12-22 08:15 UTC, kdomo commented on src/main/java/com/depromeet/domain/member/domain/Member.java
> +    private final List<Mission> missions = new ArrayList<>();
final이 왜 들어가야하는지 궁금합니다 !

2023-12-22 08:32 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    @Column(name = "sort", nullable = false)
넵넵 맞습니다 저번에 필드명을 order로 할까 했었다가 수정을 못했네요 저 부분도 수정해놓겠습니다!

2023-12-22 08:32 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    @Column(columnDefinition = "text", nullable = false)
아 기획방향 확정전에 남았던 코드네요 text 없이 수정해두겠습니다!

2023-12-22 08:33 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/member/domain/Member.java
> +    private final List<Mission> missions = new ArrayList<>();
final은 회원별 미션에 대해서 가변성을 막기 위해 추가했습니다
혹시나 mission에 대한 수정 이력이 발생하지 않도록 했었습니다!

2023-12-22 09:05 UTC, kdomo requested changes

2023-12-22 09:05 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/domain/MissionCategory.java
> +    ETC("기타");
23.12.22 기준 카테고리 목록이
운동, 공부, 글 읽기, 글 쓰기, 프로젝트/작업, 영상보기 / 팟캐스트 듣기, 기타
이렇게 변경되었네요
기존과 다른점은 프로젝트/작업이 추가되었습니당

2023-12-22 09:05 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/member/domain/Member.java
> +    private final List<Mission> missions = new ArrayList<>();
아 final을 추가함으로서 단점도 알아봤는데 lazy loading 이슈가 존재할 수도 있다네요
final은 빼도록 하겠습니다!

2023-12-22 11:51 UTC, uwoobeat requested changes

2023-12-22 11:51 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    @Enumerated(EnumType.STRING)
엔티티 칼럼 순서도 맞춰주면 좋을 것 같습니다
pk -> 일반 컬럼 -> enum -> 일대다/다대일

2023-12-22 11:51 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    @Enumerated(EnumType.STRING)
++ 생성자 파라미터에도 순서변경이 있으면 반영 부탁드립니다

2023-12-22 12:20 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    @Enumerated(EnumType.STRING)
@uwoobeat 엔티티 칼럼 순서는 어떤 기준인가용?
따로 가이드가 있나 해서 여쭤봅니다!

2023-12-22 12:33 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    @Enumerated(EnumType.STRING)
@uwoobeat 
pk -> 일반 컬럼 -> enum -> 시간(localDateTime) 컬럼 -> 일대다/다대일 컬럼 이렇게 진행해도 될까요??

2023-12-22 13:34 UTC, kdomo requested changes

2023-12-22 13:34 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +    private String content;
기획서 기준 미션 내용 null 가능하네용

2023-12-22 14:23 UTC, uwoobeat approved these changes
lgtm

2023-12-22 15:20 UTC, kdomo approved these changes
LGTM~
고생하셨슴니당

2023-12-22 16:18 UTC, merged