feat: Querydsl 환경 구성 추가
depromeet/10mm-server pull request #64
Opened 2023-12-14 15:43 UTC by uiurihappy

## 🌱 관련 이슈
- close #61 

## 📌 작업 내용 및 특이사항
- gradle querydsl 환경 구성
- QuerydslConfig 생성
- complieJava 실행 시 record compile이 안되는 이슈로 Profile 클래스 변경

## 📝 참고사항
- 

## 📚 기타
-

2023-12-20 17:28 UTC, kdomo requested changes
build.gradle에서 QueryDSL 빌드도 설정 부탁드립니다!

2023-12-20 17:36 UTC, uiurihappy commented
> build.gradle에서 QueryDSL 빌드도 설정 부탁드립니다!

@kdomo 
설정이라 하면 이 [링크](https://velog.io/@minjung0/JavaSpringBoot-%EC%9D%B8%ED%85%94%EB%A6%AC%EC%A0%9C%EC%9D%B4-Gradle-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EC%97%90-Querydsl-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)처럼 수정사항을 말씀하신 걸까요?

2023-12-20 17:47 UTC, kdomo commented
@uiurihappy 넵 맞습니당

2023-12-21 12:48 UTC, uwoobeat requested changes

2023-12-21 13:25 UTC, uwoobeat requested changes

2023-12-21 13:25 UTC, uwoobeat commented on .gitignore
> +*.DS_Store
`/src/main/generated/` 도 추가해주면 좋을 것 같습니다

2023-12-21 13:36 UTC, uiurihappy commented on .gitignore
> +*.DS_Store
@uwoobeat 
수정완료용

2023-12-22 05:30 UTC, uwoobeat approved these changes
LGTM

2023-12-22 05:33 UTC, merged