chore: 공통 상수 Enum으로 관리
depromeet/10mm-server pull request #71
Opened 2023-12-21 11:41 UTC by kdomo

## 🌱 관련 이슈
- close #69 

## 📌 작업 내용 및 특이사항
- 공통으로 쓰이는 상수를 Enum으로 관리합니다.
- [ ] #70 내용도 공통 상수 적용 예정

2023-12-21 13:01 UTC, uwoobeat requested changes

2023-12-21 13:01 UTC, uwoobeat commented on src/main/java/com/depromeet/global/common/constants/TenminuteConstants.java
> +public enum TenminuteConstants {
각각의 상수를 관심사에 맞게 관리할 수 있도록 TenminuteConstants가 보다는 UrlConstants 같은 네이밍으로 두면 좋을 것 같습니다. 그냥 TenminuteConstants라고 하면 애플리케이션에서 사용되는 모든 상수를 이 열거형에 추가해야 하는 것처럼 보일 수도 있으니까요

2023-12-21 13:04 UTC, kdomo commented on src/main/java/com/depromeet/global/common/constants/TenminuteConstants.java
> +public enum TenminuteConstants {
애플리케이션에서 사용되는 모든 상수를 해당 열거형에서 관리하려고 했는데,
관심사에 맞도록 분리하는거 좋은 것 같네용!
수정하겠습니다 🙇🏻

2023-12-22 07:18 UTC, uiurihappy approved these changes
LGTM

2023-12-22 11:46 UTC, uwoobeat approved these changes
LGTM

2023-12-22 18:09 UTC, merged