chore: application yml 환경별로 분리
depromeet/10mm-server pull request #72
Opened 2023-12-21 12:52 UTC by kdomo

## 🌱 관련 이슈
- close #52 

## 📌 작업 내용 및 특이사항
- application.yml을 환경변로 분리했습니다.
```yaml
spring:
  profiles:
    group:
      test: "test"
      local: "local, datasource"
      dev: "dev, datasource, actuator"
      prod: "prod, datasource, actuator"
```
기본 `application.yml`파일에서 위와같이 그룹을 통해서 중복 코드를 제거할 수 있습니다.
새로운 환경의 yml파일이 필요하다면 추가해주시면 됩니다.

```yaml
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
```
와 같은 방법은 분리하려했는데 중복코드가 많아서 사용하지 않았습니다

+ 놓친 설정이 있다면 알려주세용 😆

2023-12-21 13:22 UTC, uwoobeat requested changes

2023-12-21 13:22 UTC, uwoobeat commented on src/main/resources/application-datasource.yml
> +    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
먼저 `MySQL5InnoDBDialect` 의 경우 deprecated 되었습니다. [레퍼런스](https://javadoc.io/doc/org.hibernate/hibernate-core/5.6.15.Final/org/hibernate/dialect/package-summary.html)

![image](https://github.com/depromeet/10mm-server/assets/91878695/925ef0a8-7a4a-4c66-b993-c06d3a2958e0)

위 MySQL 5.x 이상 버전을 사용하는 경우 MySQLDialect를 사용하라고 되어있습니다.

뿐만 아니라 데이터베이스 방언을 직접 지정하는 것은 좋은 방식이 아닙니다. 하이버네이트 버전업에 따라서 deprecation이 이루어질 수 있기 때문에 그렇습니다.

공식 문서에서는 이렇게 말하고 있습니다. ([링크](https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#database-dialect))

> In most cases Hibernate will be able to determine the proper Dialect to use by asking some questions of the JDBC Connection during bootstrap. For information on Hibernate’s ability to determine the proper Dialect to use (and your ability to influence that resolution), see [[Dialect resolution](https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#portability-dialectresolver)](https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#portability-dialectresolver).
> 
> 
> If for some reason it is not able to determine the proper one or you want to use a custom Dialect, you will need to set the `hibernate.dialect` setting.
> 
> 대부분의 경우 Hibernate는 부트스트랩 과정에서 JDBC 커넥션에 몇 가지 질문을 던짐으로써, 적절한 Dialect를 결정할 수 있습니다. Hibernamte가 어떻게 적절한 dialect를 결정할 수 있는지에 대해서 알고 싶다면 Dialect resolution을 참고하세요.
> 
> 어떤 이유로 **“적절한 방언을 결정할 수 없거나”** **“사용자 정의 방언을 사용하고 싶다면”** 방언을 명시적으로 설정해야 합니다.


즉, 방언을 설정 파일에 명시해야 하는 경우는 위 두 가지로만 제한됩니다. 두 상황 모두 특이한 케이스이고, 대부분의 경우에는 특별하게 방언을 따로 지정해줘야 하는 경우가 존재하지 않습니다. 따라서 MySQL의 방언 설정 역시 제거해주는 것이 좋지 않을까 싶습니다.

2023-12-21 13:22 UTC, uwoobeat commented on src/main/resources/application-datasource.yml
> +    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false
환경에 따라서 다른 url이 들어가나요?

2023-12-21 13:30 UTC, kdomo commented on src/main/resources/application-datasource.yml
> +    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
몰랐던 정보네요 감사함니당

2023-12-21 13:30 UTC, kdomo commented on src/main/resources/application-datasource.yml
> +    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false
네네 datasource yml 자체를 local,dev,prod 환경에서 다 사용해서
환경변수에서 다른 url을 넣어주어야 합니당

2023-12-22 11:46 UTC, uwoobeat approved these changes
lgtm

2023-12-26 13:05 UTC, uiurihappy approved these changes
LGTM 👍

2023-12-26 13:32 UTC, merged