Feature/74 mission service
depromeet/10mm-server pull request #77
Opened 2023-12-26 12:39 UTC by uiurihappy

## 🌱 관련 이슈
- close #74 

## 📌 작업 내용 및 특이사항
- 미션 CRUD 기능 구현
  - 미션 생성
  - 미션 단건 조회
  - 미션 리스트 조회
  - 미션 수정
  - 미션 삭제
- 미션 리스트 조회 기능은 Slice로 처리
- missionApi는 interface로 추상화하여 missionController에서 Override하여 구현
- 미션 데이터 모델은 dto 패키지 내 request, response 패키지로 구분

## 📝 참고사항
- 

## 📚 기타
-

2023-12-30 10:42 UTC, kdomo requested changes

2023-12-30 10:42 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/controller/MissionController.java
> +        return missionService.addMission(createMissionRequest);
add, find, list, modify, remove 등등 컨벤션 논의 필요
@uiurihappy  @uwoobeat

2023-12-30 10:42 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/service/MissionService.java
> +    }
해당 메소드는 modifyMissionRequest의 내용으로 덮어쓰는거라
Patch보다는 Put메소드가 적합해보입니당

2023-12-30 10:42 UTC, kdomo commented on src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
> +                        .contains("Value too long for column \"NAME CHARACTER VARYING(20)\""));
```java
assertThatThrownBy(() -> missionService. addMission(createMissionRequest))
					.isInstanceOf(DataIntegrityViolationException.class);
```
와 같이 exception으로 검증하는 방법이 좋을 것 같아요오

2023-12-30 10:42 UTC, kdomo commented on src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
> +    void 미션_삭제_성공() {
모든 테스트에서 해피케이스 외 케이스도 작성하면 좋을 것 같아욥

2023-12-30 10:42 UTC, kdomo commented on build.gradle
> +    implementation 'org.projectlombok:lombok'
왜 바꿨는지 궁금해요 👀

2023-12-30 10:42 UTC, kdomo commented on build.gradle
> +    testAnnotationProcessor 'org.projectlombok:lombok' //추가
요건 테스트 환경에서 lombok을 사용하기 위해서인가요?
추가하지 않으면 어떤걸 사용못하는지 궁금해용

2023-12-30 13:12 UTC, uiurihappy commented on build.gradle
> +    implementation 'org.projectlombok:lombok'
테스트 코드 단에서 lombok를 제대로 불러오지 못한 이슈가 있어서 바꿨습니다
그런데 조금 더 살펴보니
https://dev-coco.tistory.com/105
위 링크와 같은 케이스로도 해결할 수 있고, 
Gradle 7부터는 제가 수정한 코드보다 초기 작성된 complileOnly와 annoationProcecssor를 둘 다 작성하는 것이 좋다고 하네요

둘 다 작성하는 방향으로 수정을 해두겠습니다!

2023-12-30 13:13 UTC, uiurihappy commented on build.gradle
> +    testAnnotationProcessor 'org.projectlombok:lombok' //추가
네 맞습니다 그래서 위 코멘트대로 수정하려고 합니당

2023-12-30 13:14 UTC, uiurihappy commented on src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
> +    void 미션_삭제_성공() {
넵넵 아직 생성에 대한 실패 케이스만 작성했었는데
다른 엔드포인트마다 케이스를 작성해주겠습니다!

2023-12-30 13:15 UTC, uiurihappy commented on src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
> +                        .contains("Value too long for column \"NAME CHARACTER VARYING(20)\""));
아 저 방법이 있었네요 참고로 하여 수정 후 테스트 진행해보겠습니다!

2023-12-30 13:16 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/service/MissionService.java
> +    }
아하 그렇군요 API 명세서에도 작성을 했었는데 임의로 제가 처리했나봅니다
수정해두겠습니다!

2023-12-30 13:17 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/api/MissionApi.java
> +            @PathVariable(value = "missionId") Long missionId);
아하 저는 value를 명시하는게 조금 더 명확한 네임을 볼 수 있다 생각해서 넣었습니다

2023-12-30 13:21 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/api/MissionApi.java
> +            @RequestParam int size, @RequestParam(required = false) Long lastId);
제가 생각한 지금 미션 목록에 대한 기획은 페이지네이션이 아닌 무한 스크롤 방식을 사용하고 있어보이고,
그리고 Pageable을 사용할 시 page 카운트 쿼리도 추가 발생하기에 마지막 Slice가 존재하는 지에 대한 여부로는
Slice가 적합하다고 생각했습니다!

2023-12-30 13:25 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/api/MissionApi.java
> +@Valid
음 이 부분은 DTO에서도 걸어놨지만, 클래스 전체에 @Valid를 걸었던 게 혹여나 DTO에 미처 못걸어 Validate가 안되는 케이스가 있을까봐 걸어놓은 거 같아요

명확하게 하려면 클래스보다는 메서드 내부에 있는 Argument에만 거는 것이 낫다고 보는 데 어떻게 생각하실까요?

2023-12-30 13:26 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/api/MissionApi.java
> +    @PostMapping("")
관례적으로 사용하다보니 저렇게 작성했었는데 팁 감사합니다:)

2023-12-30 13:33 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/api/MissionApi.java
> +public interface MissionApi {
저도 지금 이 부분은 많은 고민이 있었는데, 앞으로 나아가 Controller 단에서 분리할만큼 명확한 이유를 특정짓기는 어렵네요
다시 Controller로 수정해두고 만약 필요한 로직이 있다면 다시 분리하는 방법으로 가도 좋을 거 같습니다!

2023-12-30 13:57 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/api/MissionApi.java
> +            @RequestParam int size, @RequestParam(required = false) Long lastId);
앗 제가 말씀드린건 파라미터로 받는 size와 lastId 대신 Pageable 객체를 파라미터로 받는걸 이야기했었던거였어용!
return을 슬라이스로 하는건 저도 동의함니다~~

2023-12-30 13:59 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/controller/MissionController.java
> +        return missionService.addMission(createMissionRequest);
그러네용 지금 식사 이슈 해결하시고 좀 이따 잠깐 논의하죠 👍

2023-12-30 14:01 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/api/MissionApi.java
> +            @RequestParam int size, @RequestParam(required = false) Long lastId);
아아 그렇군요 
queryString을 Pageable 객체로 받는 걸 생각못했었네요
수정해보겠습니다!

2023-12-30 14:01 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/dto/response/MissionResponse.java
> +        @Schema(description = "미션 ID") Long missionId,
넵 피드백 감사해용

2023-12-30 15:55 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/api/MissionApi.java
> +@Valid
@uiurihappy 
네네 저도
```java
public Mission missionAdd(@Valid CreateMissionRequest createMissionRequest) {
    ....
}
```
의 형태로만 사용하는게 좋은거같아용~

2023-12-31 08:53 UTC, kdomo requested changes

2023-12-31 08:53 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/controller/MissionController.java
> +public class MissionController {
기존 패키지 구조와 같이 `api` 패키지로 옮겨주세요오

2023-12-31 08:53 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/controller/MissionController.java
> +    public Mission missionCreate(@Valid MissionCreateRequest missionCreateRequest) {
controller에서 domain 객체를 의존하기보다 service레이어에서 dto를 응답받는게 좋을거같아용

2023-12-31 08:53 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
> +    }
Pageable 객체에 size와 page가 존재하는데 lastId를 따로 만들어서
lt연산을 사용하신 이유가 있을까용?

pageable객체에 page값을 통해 offset이 아닌 
lastId를 받아 where을 통해 lt연산을 한 이유가 궁금합니당👀

2023-12-31 08:53 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +        }
Custom 예외를 사용하면 조을거같은데 어떻게 생각하세염?

2023-12-31 08:53 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/dto/response/MissionFindResponse.java
> +        @Schema(description = "미션 정렬 값", defaultValue = "1") Integer sort) {
`MissionCategory`, `MissionVisibility` enum을 response하지 않고
String으로 넘겨주시는 이유가 궁금함니당

2023-12-31 08:53 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/dto/request/MissionCreateRequest.java
> +                MissionVisibility visibility) {}
MissionCategory = `EXERCISE`
MissionVisibility = `ALL`과 같이 defaultValuer를 enum에 맞는 값을 넣어주셔야 할것같아요!

2023-12-31 08:53 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/controller/MissionController.java
> +    public Mission missionCreate(@Valid MissionCreateRequest missionCreateRequest) {
`@RequestBody` 빠져있습니당

2023-12-31 08:53 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/service/MissionService.java
> +                        memberUtil.getCurrentMember());
memberUtil.getCurrentMember() 에서 query를 사용하기 때문에
위쪽에서
```java
final Member currentMember = memberUtil.getCurrentMember();
```
로 선언 후 사용하는게 좋아보임니당

2023-12-31 10:18 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/controller/MissionController.java
> +public class MissionController {
넵 알겠습니다!

2023-12-31 10:19 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/controller/MissionController.java
> +    public Mission missionCreate(@Valid MissionCreateRequest missionCreateRequest) {
아 엔티티를 그대로 노출하는거보다 낫겠네용 
수정해두겠습니다!

2023-12-31 10:19 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/domain/Mission.java
> +        }
그럼 Custom enum 타입을 추가해서 예외처리 진행보겠습니다!

2023-12-31 10:26 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
> +    }
lastId로 마지막 객체의 id(lastId)를 받아 lt연산을 하면 
lastId부터 pageable에서 받은 size 값만큼 API 콜을 하기 때문입니다. 

ex) 50번부터 40번의 id로 초기 페이지를 렌더링 하였고, 
다음 객체 리스트를 조회하기 위해 lastId인 40번을 lt연산으로
pageable 내에 size값 만큼 호출하는 방식으로 무한 스크롤을 구성하였습니다.

```sql
where missionId < 40
order by missionId desc limit 받은 size + 1
```

pageable에는 lastId가 없어 RequestParam으로 lastId를 받아 사용하려 했습니다!

2023-12-31 10:27 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/dto/response/MissionFindResponse.java
> +        @Schema(description = "미션 정렬 값", defaultValue = "1") Integer sort) {
MissionVisibility 예시로 enum 객체 그대로 response 해주면 프론트엔드는 ALL, FOLLOWER, NONE의 값을 받기에
받은 String 그대로 렌더링 할 수 있도록 String 객체를 response 해주도록 구현했습니다.

2023-12-31 10:28 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/dto/request/MissionCreateRequest.java
> +                MissionVisibility visibility) {}
아 자료형이 enum으로 되어있는데 defaultValue를 잘못넣었네요
수정해두겠습니다!

2023-12-31 10:29 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/controller/MissionController.java
> +    public Mission missionCreate(@Valid MissionCreateRequest missionCreateRequest) {
이런... 초보적인... 얼른 넣겠습니다!

2023-12-31 10:29 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/service/MissionService.java
> +                        memberUtil.getCurrentMember());
오 그렇네요
선언후에 넣도록 진행하겠습니다!

2023-12-31 11:17 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/dto/response/MissionFindResponse.java
> +        @Schema(description = "미션 정렬 값", defaultValue = "1") Integer sort) {
아마 프론트에서 요청 보낼때 ALL, FOLLOWER 등과 같은 값을 보내줘야해서
return할 때도 해당 값으로 return해도 괜찮을 것 같은데
해당 파트 담당자와 논의 후 알려주시면 감사하겠슴니당

2023-12-31 13:35 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
> +    }
pageable에 는 page와 size가 있는데 보통 페이징 처리할때 page를 offset으로 사용해서,
lastId를 따로 구현하신 이유가 있는지 궁금했어용

지금과 같이 한다면 요청보낼 때, page = null, size = n , lastId = m 요런식으로 되게되는데,
lastId대신 page를 사용하여 offset 처리하는게 좋아보이는데 어떻게 생각하세용?

2023-12-31 16:39 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
> +    }
저는 offset을 사용하지 않았던 게 아래와 같은 사유로 offset을 사용하지 않았었어요
그런데 만약 리스트에서 정렬조건이 더 추가로 발생하거나 유지보수성으로 offset 사용이 맞을 거 같은데
한번 확인 해주시고 아젠다로 논의해보는 것은 어떨까요??

참고링크
- https://xrabcde.github.io/pagination/
- https://binux.tistory.com/148

2024-01-01 11:52 UTC, kdomo requested changes
비지니스 로직은 다음 PR에서 구현하시는거 맞죠???!

2024-01-01 11:52 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
> +    }
@uiurihappy
오 이런이유였군요
그렇다면 Pageable 대신에 기존 구현하신대로 size와 lastId만 받는게 좋아보이네용!!

2024-01-01 11:52 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/service/MissionService.java
> +                missionRepository.findTopByMemberOrderBySortDesc(memberUtil.getCurrentMember());
```suggestion
        Mission missionByMaxSort =
                missionRepository.findTopByMemberOrderBySortDesc(member);
```
요기 수정안되었어용

2024-01-01 11:52 UTC, kdomo commented on src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
> +    }
미션 삭제 실패는 어떤 경우인가요?

2024-01-01 12:44 UTC, uiurihappy commented on src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
> +    }
존재하지 않는 mission의 Id를 받는 경우를 작성해봤어요!

2024-01-01 12:46 UTC, uiurihappy commented
> 비지니스 로직은 다음 PR에서 구현하시는거 맞죠???!

넵 맞습니당 다음 PR부터는 쪼개서 고도화를 해야할 거 같아용

2024-01-01 13:42 UTC, kdomo commented on src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
> +    }
테스트코드 메소드 네이밍
`미션_삭제시_존재하지_않는_아이디라면_삭제되지_않는다`와 같이
다른것들도 다 맞춰주시면 더 좋을것같습니다!! `미션_삭제_실패` 만보고는 유추하기가 좀 어려운거같아서요!!

2024-01-01 13:44 UTC, uiurihappy commented on src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
> +    }
오 좋은 네이밍 감사합니다:) 반영하도록 할게용

2024-01-01 14:02 UTC, kdomo requested changes

2024-01-01 14:02 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/api/MissionController.java
> +    }
생성이라 CREATED 응답하면 더 좋을 것 같슴니다아

2024-01-01 14:02 UTC, kdomo commented on src/main/java/com/depromeet/domain/mission/api/MissionController.java
> +        return missionService.findAllMission(pageable, lastId);
위에서 이야기 했던것처럼
Pageable에서 page를 사용하지 않으니
size, lastId만 두는게 좋아보임니당

2024-01-01 14:28 UTC, kdomo approved these changes
고생하셨슴니다🙇🏻

2024-01-01 14:29 UTC, uiurihappy commented
> 고생하셨슴니다🙇🏻

@kdomo 
도모님도 리뷰해주시느라 고생많으셨고 감사합니당👍

2024-01-01 16:03 UTC, uwoobeat requested changes
수고하셨습니다!

1. DTO 검증 테스트가 필요할 것 같습니다. (컨트롤러에서 테스트해야 합니다)
2. 레포지터리 레이어에 대한 테스트가 필요합니다. (QueryDsl 등으로 직접 작성한 경우)

추가로 리뷰할 부분이 있으면 알려드릴게요~

2024-01-01 18:03 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
> +    Optional<MissionFindResponse> findByMissionId(Long missionId);
기획서에는 미션 상세보기에 대한 명세는 없지만, 
만약 미션 단건 조회같은 경우 미션 내역도 필요할 듯하여 join을 위해 Querydsl로 사용하였습니다!

2024-01-01 18:43 UTC, uiurihappy commented on src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
> +class MissionServiceTest {
단독적으로 MissionServiceTest 코드에서만 MOCK을 사용하였는데, MemberUtilTest단에서도 MOCK을 걸어줘야 하는 번거로움이 존재합니다! 혹시 이 점 괜찮으실까요?

2024-01-02 15:51 UTC, uwoobeat approved these changes
lgtm

2024-01-02 15:54 UTC, merged