feat: 미션 기록 저장 기능 구현
depromeet/10mm-server pull request #97
Opened 2024-01-03 09:48 UTC by kdomo

## 🌱 관련 이슈
- close #87 

## 📌 작업 내용 및 특이사항
- 미션 기록 저장 API입니다.
- Validation 의존성 없어서 추가해두었습니다.
- 해당 PR에서는 미션 기록 저장만 존재하고, 이미지와 일지는  #95 이슈 처리 후 작업하도록 하겠습니다.
- 이벤트 발행 및 Redis 관련 처리는 #88 머지 후 작업 예정
- 우선 domain test만 작성해두었습니다 추 후 새로운 이슈에서 Controller, Service 테스트 작성하겠슴니다.
- duration은 분과 초를 나누어서 받도록 프론트 @sumi-0011 와 협의 완료

2024-01-03 13:58 UTC, uwoobeat requested changes

2024-01-03 13:58 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
> +            Integer durationMin,
Duration 클래스 사용하는 것은 어떨까요?

2024-01-03 13:58 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
> +        if (duration > 3600) {
3600 넘으면 정책적으로 막는 편이 낫지 않을까요? 프론트에서는 3600까지만 보내게 하고...

2024-01-03 14:01 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
>      }
지금 createMissionRecord 메서드에 
인증 사진 imageUrl이 builder에서 삭제되었는데, 일단 저도 다시 리마인드하면서 imageUrl은 builder에서 없는게 맞는 거 같아요

그런데 지금 컬럼에는 nullable = false로 제가 구현했었는데 nullable false 옵션 지워주시면 감사하겠습니다..!

2024-01-03 14:03 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
> +        if (duration > 3600) {
저도 정책적으로 막는것에 동의해요 👍🏻
하지만 프론트에서 모종의 이유로 인해 3600이 넘어가는 값이 넘어왔을 때, 예외로 처리하는게 좀 고민이 되네요 ㅜ
재현님은 어떻게 생각하시나요?

2024-01-03 14:10 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
> +            Integer durationMin,
Duration을 사용했을 때 이점이 어떤게 있을까요?

domain 객체의 정펙메 createMissionRecord의 매개변수로 Duration을 받게된다면
Service 레이어에서 입력받은 분과 초를 통해 Duration을 생성하고 파라미터로 넘겨 받은 domain객체의 정펙메 createMissionRecord에서는 Duration으로 되어있는 값을 통해 Entity에 멤버변수인 Integer duration에 저장하기 위해
다시 값을 꺼내와야하는데

Duration을 사용하는게 여기서는 래핑하고 언래핑하는 과정만 추가될 것 같은데 다른 이점이 있을까용??

2024-01-03 14:12 UTC, uiurihappy commented on src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
> +
```java
final Mission mission =
                missionRepository
                        .findByMissionId(request.missionId())
                        .orElseThrow(() -> new CustomException(ErrorCode.MISSION_NOT_FOUND));
```

findByMissionId를 사용하는 이 코드들은 Method로 분리하는 것은 어떨까요??
나중에 missionRecordService 내 다른 메서드에서 사용할 수 있을 거 같아서용

2024-01-03 14:16 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
> +    }
id값만 넘겨주도록 수정하겠슴니당

2024-01-03 14:19 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
>      }
확인 감사합니당🙇🏻

2024-01-03 14:20 UTC, kdomo commented on src/test/java/com/depromeet/domain/missionRecord/domain/MissionRecordTest.java
>                          "testMissionName",
미션쪽 날짜 검증이 없어서 테스트 통과했군용ㅋㅋㅋㅜ
테스트 통과해서 넘어갔는데 실수했네용 수정해두겠슴니당

2024-01-03 14:33 UTC, uiurihappy commented on src/test/java/com/depromeet/domain/missionRecord/domain/MissionRecordTest.java
>                          "testMissionName",
말씀하시니까 저도 번뜩 떠올라서
나중에라도 startedAt <= finishedAt 인 조건에 대한 예외도 있으면 좋을 거 같네용

당장은 2차 MVP라 제가 말씀드렸던 내용만 반영해주셔도 좋을 거 같습니다!

2024-01-03 14:51 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
> +        if (duration > 3600) {
3600이 넘어가는 값이 넘어오면 프론트 잘못이라고 생각해서, 예외 터트리는게 맞지 않을까 싶어요

2024-01-03 14:57 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
> +        if (duration > 3600) {
넵 고럼 고렇게 처리하고 프론트 담당자에게 전달해두겠슴니당~

2024-01-03 15:04 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
> +            Integer durationMin,
Duration클래스를 사용하면 어떤 이점이 있을지 궁금합니다!

Duration을 사용할 때 여러가지 문제점이 생겼는데용..
1.현재 `createMissionRecord`의 파라미터로 Duration을 받게되면 Service 레이어에서 입력받은 분,초를 Duration으로 래핑해줘야하는데 래핑해준 뒤 createMissionRecord에서는 언래핑 하는 과정이 추가로 생기네요
2.Duration의 getSeconds메소드는 long 값을반환하는데 Entity에서 duration은 Integer를 사용하기때문에 강제로 다운캐스팅을 해줘야하는 과정이 추가되는데 비지니스 관점에서 int범위를 넘어가는 duration값이 존재하지 않다는것을 알지만 더 큰 범위의 long 값을 강제로 다운캐스팅해서 사용하는게 맞을까? 라는 의문이 들어용
3.Controller에서 RequestBody 받을 때 Duration을 받게되면 아래 이미지와 같이 요청 본문이 길어지네용
![image](https://github.com/depromeet/10mm-server/assets/64088250/69f547b6-fc03-4162-aa30-38330af8c1f0)

2024-01-03 15:14 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
> +            Integer durationMin,
1. 엔티티의 duration 필드에 Duration 타입을 사용하는 것은 불가능한가요? 서비스 레이어에서 분, 초를 Duration으로 매핑해주고 그래도 할당이 가능하다면 해결 가능하지 않을까 싶습니다
2. 마찬가지로 Entity에서 Duration 타입 사용한지에 따라 해결 가능한지 여부가 달라질 것 같아요
3. request body에서는 min, sec만 받고 서비스 레이어 or 컨트롤러 파라미터 단에서 매핑해주면 어떨까요?

2024-01-03 15:22 UTC, kdomo commented on src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
> +            Integer durationMin,
엔티티의 duration을 사용하게되면 decimal을 사용하는데 이것보다
차라리 Duration을 사용하고 entity에 duration을 Long타입으로 바꾸는게 어떨까요?

2024-01-03 15:29 UTC, uwoobeat commented on src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
> +            Integer durationMin,
DB의 DECIMAL 타입을 사용했을 때 예상되는 문제가 있나요? Duration을 쓰는 편이 의미적으로 더 적절할 것 같아서요.

2024-01-04 06:09 UTC, uiurihappy approved these changes
제가 요청드렸던 내용은 다 반영되서 
✅LGTM✅

2024-01-04 10:30 UTC, uwoobeat approved these changes
lgtm

2024-01-04 10:42 UTC, merged